=pod

=head1 NAME

xde-xlock - screen locker for X Desktop Environment (XDE)

=head1 SYNOPSIS

B<xde-xlock> [I<OPTIONS>]

=head1 DESCRIPTION

B<xde-xlock> is a screen locker replacement that provides tight
integration with the L<systemd(8)> multi-session environment.  It acts as
a screen-saver locker, detects L<logind(8)> C<Lock> signals, and
performs locking on VT switches.

=head1 OPTIONS

=head2 COMMAND OPTIONS

Command options affect the major operating mode of the program.  Only
one command option may be specified (with the exception that B<--help>
can be specified in conjunction with any other command option).  When no
command option is specified, B<--locker> is assumed.  The command
options recognized by the program are as follows:

=over 4

=item [B<-L>, B<--locker>]

Run continuously as a screen locker instance.  This process will monitor
for screen locking requests, screen saver activation and virtual
terminal changes and will invoke screen locking as appropriate.

=item B<-r>, B<--replace>

Replace a currently running screen locker instance with the current
process.

=item B<-l>, B<--lock>

Ask a running instance to lock the screen now.

=item B<-q>, B<--quit>

Ask a running instance to exit.

=item B<-H>, B<-help>

Instead of operating normally, the program prints usage information to
standard output and exits.

=item B<-V>, B<--version>

Instead of operating normally, the program prints detailed version
information and exits.

=item B<-C>, B<--copying>

Instead of operating normally, the program prints detailed copying
permissions and exits.

=back

=head2 GENERAL OPTIONS

General options can be specified in conjunction with any command option.
The general options recognized by the program are as follows:

=over 4

=item B<-p>, B<--prompt> I<PROMPT>

Specifies the pango markup text that is to be displayed in the title
area of the unlock panel.  The default is C<Welcome to %s!>, where
C<%s> is the fully qualified domain name of the current host.

=item B<-b>, B<--banner> I<BANNER>

Specifies the banner graphic to display in the left pane of the unlock
panel.  The default is obtained by looking for the file
F<${XDG_MENU_PREFIX}banner.png> in the F<images> subdirectory of
standard XDG data directories, F<$XDG_DATA_DIRS>.  See L</ENVIRONMENT>.

=item B<-s>, B<--side> {B<left>|B<top>|B<right>|B<bottom>}

Specifies the side of the window on which the banner logo will be
placed.  The default is B<left>.  Although this option may be specified,
the program ignores any setting other than B<left>.

=item B<-S>, B<--splash> I<SPLASH>

Specifies the background image, I<SPLASH>, to display on the lock
screen.  The default is to use the background image currently installed
on the screen, and if no background image is installed on the screen, to
search for the background image file in the file named
F<${XDG_MENU_PREFIX}splash.png> in the F<images> subdirectory of
standard XDG data directories, F<$XDG_DATA_DIRS>.  See L</ENVIRONMENT>.

=item B<-n>, B<--dry-run>

Specifies that the program should not perform any actions but should
simply print intentions to standard output.  This option is for testing.

=item B<-D>, B<--debug> [I<LEVEL>]

Increase, or set to I<LEVEL>, the debugging verbosity.  The default
debugging verbosity level is zero (0), which means to output no
debugging information.  When non-zero, debugging information will be
printed to standard error.

=item B<-v>, B<--verbose> [I<LEVEL>]

Increase, or set to I<LEVEL>, the output verbosity.  The default output
verbosity level is one (1), which means to output normal information to
standard output.  When set to zero (0), no output will be printed to
standard output. 

=back

=head1 X RESOURCES

Most values that affect the look and feel of B<xde-xlock> may also be
specified as X resources in the B<RESOURCE_MANAGER> database associated
with the X server.  All of these resources can have the specific
resource name and class (C<xde-xlock>, B<XDE-XLock>).  When no resource
is found with the specific name and class, L<xdm(1)> resources with name
and class (C<xlogin.login>, C<Xlogin.login>) will also be examined for
specified resources.

Note that L<xdm(1)> usually adds the resources contained in the
F</etc/X11/xdm/Xresources> file that is loaded by L<xdm(1)> on startup
to the resource database on the X server.  Chooser resource defaults
(see also L<xdm(1)> and L<xde-xlogin(1)> are contained in the
F</usr/share/X11/app-defaults/Chooser> file.  Likewise, B<xde-xlock>
specific resource defaults are contained in the
F</usr/share/X11/app-defaults/XDE-XLock> file, in accordance with the
convention of naming applications default files after their resouce
class.  See also L</FILES>.

B<xde-xlock> observes the following X11 Resource Manager resources when
loaded by L<xdm(1)> prior to execution:

=over 4

=item B<xde-xlogin>.B<x>: I<DOUBLE>

Specifies the X position on the monitor as a floating point number
between C<0.0> and C<1.0>, where C<0.0> represents the left edge of the
monitor and C<1.0>, the right edge.  The dialog will be positioned on this
point depending on its gravity (currently static or centered).

=item B<xde-xlogin>.B<y>: I<DOUBLE>

Specifies the Y position on the monitor as a floating point number
between C<0.0> and C<1.0>, where C<0.0> represents the top edge of the
monitor and C<1.0>, the bottom edge.  The dialog will be positioned on
this point depending on its gravity (currently static or centered).

=item B<xde-xlogin>.B<debug>: I<INTEGER>

Provides the debugging level in the same fashion as the B<-debug>
command line option.

=item B<xde-xlogin>.B<banner>: I<PATH>

Provides the banner to use for the branding logo in the same fashion as
the B<-banner> command line option.  Specifies the I<PATH> to the banner
graphic to display in the left pane of the host menu.  When unspecified,
the program searches for an image file name
F<${XDG_VENDOR_ID--}banner.{xpm,png,jpg,svg}> in the subdirectory
F<images> in XDG data directories.

=item B<xde-xlogin>.B<splash>: I<PATH>

Provides the background to use for the root window in the same fashion
as the B<-splash> command line option.

=item B<xde-xlogin>.B<welcome>: I<MARKUP>

Provides the welcome message to use for the root window in the same
fashion as the B<-welcome> command line option.  Specifies the F<pango>
markup text, I<MARKUP>, that is to be display in the title area of the
host menu.

=item B<xde-xlogin>.B<charset>: I<CHARSET>

Provides the character set in the same fashion as the B<-charset>
command line option.

=item B<xde-xlogin>.B<language>: I<LANG>

Provides the language in the same fashion as the B<-language> command
line option.

=item B<xde-xlogin>.B<theme.icon>: I<NAME>

Provides the XDG icon theme name.
Specifies the value of the B<-icons> option.

=item B<xde-xlogin>.B<theme.name>: I<NAME>

Provides the XDG theme name (for GTK+).
Specifies the value of the B<-theme> option.

=item B<xde-xlogin>.B<theme.cursor>: I<NAME>

Provides the XDG cursor theme name.

=item B<xde-xlogin>.B<theme.xde>: {B<true>|B<false>}

When I<true>, specifies that the system XDE desktop theme should be used
instead of the system GTK+ theme.
Specifies the value of the B<-xde-theme> option.

=item B<xde-xlogin>.B<side>: {B<left>|B<right>|B<top>|B<bottom>}

Specifies the side on which the logo (banner) should appear.  Currently
only I<left> is supported.
Specifies the value of the B<-side> option.

=item B<xde-xlogin>.B<user.default>: I<USERNAME>

Specifies a default use name to use for the login (when a login is
provided).  Note that a default user name will not be presented when it
can be detected that the display is remote from the current host.
Specifies the value of the B<-username> option.

=item B<xde-xlogin>.B<autologin>: {B<true>|B<false>}

When I<true>, specifies that the user defined in
B<xde-xlogin>.B<user.default> should be automatically logged into a
session without requiring a password.  It may be necessary for such a
user to be a member of the C<autologin> group.  Auto login will be
suppressed when it can be detected that the display is remote from the
current host.

=item B<xde-xlogin>.B<vendor>: I<VENDOR-ID>

Provides a vendor identifier for use in lookup up banners and
backgrounds automatically, as with the B<-vendor> command line option.

=item B<xde-xlogin>.B<prefix>: I<MENU-PREFIX>

Provides a vendor identifier as a menu prefix (C<XDG_MENU_PREFIX>)
instead of as a plain identifier.  The prefix normally has a dash (C<->)
appended.

=item B<xde-xlogin>.B<login>*B<permit>: {B<true>|B<false>}

The XDMCP Chooser has control of an X Display in the same manner as the
XDMCP Greeter program and may provide an immediate login option in
addition to a list of XDMCP hosts.  When I<true>, this option specifies
that this login is to be presented as an option to users of the XDMCP
Chooser.

=item B<xde-xlogin>.B<login>*B<remote>: {B<true>|B<false>}

The XDMCP Chooser may provide a direct login option to the user of the
chooser.  When I<true>, this option specifies that remote displays will
be given the same opportunity to log in directly.  When I<false>,
displays that are detected as remote from the host will no be offered a
direct login.

=item B<xde-xlogin>.B<xsession.chooser>: {B<true>|B<false>}

Specifies the value of the B<-xsession> option.

=item B<xde-xlogin>.B<xsession.execute>: {B<true>|B<false>}

=item B<xde-xlogin>.B<xsession.default>: I<APPID>

Specifies the value of the B<-default> option.

=item B<xde-xlogin>.B<setbg>: {B<true>|B<false>}

Specifies the value of the B<-nosetbg> option.

=item B<xde-xlogin>.B<transparent>: {B<true>|B<false>}

Specifies the value of the B<-transparent> option.

=item B<xde-xlogin>.B<face>: I<XFTFONT>

The typeface used to display the input typed by the user.
The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.face>
resource is used instead.

=item B<xde-xlogin>.B<greetFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.greetFace>
resource is used instead.

=item B<xde-xlogin>.B<greetColor>

The default is C<grey20>.
If this resource is not specified, the
B<xlogin>.B<Login.greetColor>
resource is used instead.

=item B<xde-xlogin>.B<promptFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.promptFace>
resource is used instead.

=item B<xde-xlogin>.B<promptColor>

The default is C<grey20>.
If this resource is not specified, the
B<xlogin>.B<Login.promptColor>
resource is used instead.

=item B<xde-xlogin>.B<inputFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.inputFace>
resource is used instead.

=item B<xde-xlogin>.B<inputColor>

The default is C<grey20>.
If this resource is not specified, the
B<xlogin>.B<Login.inputColor>
resource is used instead.

=item B<xde-xlogin>.B<failFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.failFace>
resource is used instead.

=item B<xde-xlogin>.B<failColor>

The default is C<red>.
If this resource is not specified, the
B<xlogin>.B<Login.failColor>
resource is used instead.
=back

When specific B<xde-xlock> resources are not specified,
B<xde-xlock> falls back the using the resources specified for its
default greeter by L<xdm(1)>, as follows:

=head1 USAGE

The B<--locker> command option (the default), or the B<--replace>
option, can be used to run the program as a background screen locker.
In this mode the program installs itself as follows:

=over 4

=item 1.

If possible, takes ownership of the B<_XDE_XLOCK_S>C<%d> manager
selections for each screen on the display.  If one of these manager
selections is already owned, the program exits with a diagnostic unless
B<--replace> was specified as a command option.

=item 2.

Installs itself as a screen saver using the C<MIT-SCREEN-SAVER>
extension on the X server (if present).

=item 3.

Installs itself as a monitoring program on the controlling terminal for
virtual terminal switches (when the X server is running on a local
virtual terminal).

=item 4.

Listens for a C<Lock> signal from the L<systemd(8)> L<logind(8)>
D-BUS service.

=item 5.

Monitors for changes.

=back

When monitoring for changes, the screen locker responds as follows:

=over 4

=item 1.

When it receives a lock request from another instance of the program, it
locks the screen immediately.

=item 2.

When the screen saver is activated, it waits for a number of seconds
after the activation and locks the screen.

=item 3.

When a C<Lock> signal is received from L<logind(8)>, over the D-BUS, it
locks the screen.

When an C<Unlock> signal is received from L<logind(8)>, over the D-BUS,
it unlocks the screen.

=item 4.

When a virtual terminal change is made to the VT on which the X server
is running, it locks the screen before permitting the switch.

=back

The B<--quit> option can be used to ask a running instance of the screen
locker to quit (remove itself and exit).

The B<--lock> option can be used to ask a running instance of the screen
locker to lock the screen.

=head1 FILES

The following files are used by the program:

=over 4

=item F<$XDG_DATA_DIRS/images/${XDG_MENU_PREFIX}banner.png>

The default location of the banner logo to display on the left of the
unlock panel.

=item F<$XDG_DATA_DIRS/images/${XDG_MENU_PREFIX}splash.png>

The default location of the background splash to display on the lock
screen when no other background is available.

=back

=head1 ENVIRONMENT

The following environment variables are considered by the program:

=over 4

=item B<XDG_VENDOR_ID>

When specified in the environment, the program will use the value of
this environment variable to form the default names of the B<--banner>
and B<--splash> files by prefixing it and a dash (C<->) to the default
banner or splash name.  This environment variable will be used in
preference to B<XDG_MENU_PREFIX> but can be overridden with the
B<--vendor> option.

=item B<XDG_MENU_PREFIX>

When specified in the environment, and neither the B<XDG_VENDOR_ID>
environment variable nor the B<--vendor> option are specified, the
program will use the value of this environment variable to form the
default names of the B<--banner> and B<--splash> files by prefixing it
to the default banner or splash name.  This environment variable will be
overridden by either of the B<XDG_VENDOR_ID> environment variable or
B<--vendor> option.

=item B<XDG_DATA_DIRS>

When specified, specifies the path of XDG data directories that will be
searched for banner or splash files.  When unspecified, defaults to
F</usr/local/share:/usr/share> in accordance with XDG specifications.

=back

=head1 BUGS

B<xde-xlock> had no known bugs at the time of release.  Please report
bugs for current versions to the source code repository at
L<https://github.com/bbidulock/xde-session/issues>.

=head1 HISTORY

I wrote B<xde-xlock> because there were no stand-alone screen lockers
that worked well with the L<systemd(8)> multi-session environment.

=head1 SEE ALSO

L<xdm(1)>,
L<xde-xlogin(1)>,
L<xde-session(1)>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

See B<--copying> for full copyright notice and copying permissions.

=head1 LICENSE

See the F<COPYING> file in the distribution or use the B<--copying> flag
to display copying permissions.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
