=pod

=head1 NAME

xde-chooser -- choose an XDG desktop session to execute

=head1 SYNOPSIS

B<xde-chooser> [I<OPTIONS>] [I<SESSION>]

=head1 DESCRIPTION

B<xde-chooser> is a C<C>-language program that can be launched from
F<~/.xinitrc> to choose the X session that will be launched, or can be
launched from a window manager or session logout script to switch the
sessions.  The menu can also provide the choice for the user to perform
actions on the box such as powering off the computer, restarting the
computer, etc.

When a selection is made or logout/disconnect is selected,
B<xde-chooser> prints the selected session name (or filename to the
xsession desktop file when B<-f> is given) or the special name C<logout>
to standard output and exits with a zero exit status.  On error, a
diagnostic message is printed to standard error and a non-zero exit
status is returned.

=head1 ARGUMENTS

B<xde-chooser> accepts one optional argument as follows:

=over

=item [I<SESSION>]

The name of the XDG session to use.  This can be any of the recognized
session names or the special names: C<logout>, C<default> or C<choose>.

=over

=item C<logout>

Do not choose a session but simply logout.  This has the effect of
simply reprinting C<logout> to standard output and exiting.

=item C<default>

Do not choose a session but simply run (typically without prompting)
whichever session the user has set as a default.  (The default is
located in the file F<$HOME/.dmrc> or F<$XDG_CONFIG_HOME/xde/default>.)
When no default is configured, or when the configured default is not
usable (e.g.  missing executable), this argument has the same effect as
C<choose>, below.

=item C<choose>

Launch a dialog to choose the session regardless of whether a default
session is configured or available.  This is the most typical mode of
B<xde-chooser>.

=item I<SESSION>

A Session name is the name of the F<*.desktop> file (without the
F<.desktop> suffix) that exists in a F<@XDG_DATA_DIRS/xsessions/>
subdirectory describing the window manager session.  Some commonly
recognized session names are as follows: C<adwm>, C<AfterStep>,
C<blackbox>, C<ctwm>, C<dwm>, C<etwm>, C<fluxbox>, C<flwm>, C<Fvwm>,
C<fvwm>, C<Fvwm1>, C<icewm>, C<jwm>, C<openbox>, C<pekwm>, C<twm>,
C<vtwm>, C<wmaker>, C<wmii>, C<wmx>, etc.

=back

When unspecified, the default is C<default>.

=back

=head1 OPTIONS

B<xde-chooser> uses L<getopt_long_only(3)> to parse options, so
abbreviated or single-dash long options are recognized when not
ambiguous.  B<xde-chooser> accepts the following options:

=head2 COMMAND OPTIONS

The following command options are mutually exclusive: the first option
in this group encountered sets the mode of the program.  When no command
option is specified, the program assumes normal operation.  In normal
operation the graphical chooser is display and once the user has
selected a session, the program exits.

=over

=item B<--help>, B<-h>

Print usage information to standard error containing current defaults
and exit.

=item B<--version>, B<-v>

Print the program version to standard output and exit.

=item B<--copying>, B<-C>

Print copying permissions to standard output and exit.

=back

=head2 CHOOSER OPTIONS

The following general options can be used with most of the command
options listed above:

=over

=item B<--default>, B<-d>

When a I<SESSION> argument is specified, also set the future default to
I<SESSION>.

=item B<--prompt>, B<-p>

Prompt the user for the session regardless of the value of the
I<SESSION> argument.

=item B<--timeout>, B<-T> I<SECONDS>

Specify the timeout in seconds that the program will wait for user input
before proceeding with the default session.  Set to zero to defeat the
timeout altogether.  The default is 15 seconds.  This option is useful
when you have multiple monitors and the B<xde-chooser> window winds up
on a monitor that is not visible to the user.  (At least some X session
will be invoked that will hopefully utilize all monitors.)

=item B<--banner>, B<-b> I<BANNER>

Specifies a custom login logo.  When unspecified, B<xde-chooser> will
use a branded logo that depends on environment variables.  This option
is compatible with L<xde-logout(1)>.

=item B<--side>, B<-s> {B<left>|B<top>|B<right>|B<bottom>}

Specifies the side of the window on which the logo will be placed.  This
option is recognized for compatibility with L<lxsession-logout(1)>.
B<xde-logout> always places the logo on the left and this option is
ignored.

=item B<--icons>, B<-i> I<THEME>

Specifies the icon theme to use.  Otherwise, the user's default gtk2
icon theme will be used (i.e. from F<$HOME/.gtkrc-2.0>); but note the
B<--xde-theme> option as well.

=item B<--theme>, B<-t> I<THEME>

Specifies the Gtk2 theme to use.  Otherwise, the user's default gtk2
theme will be used (i.e. from F<$HOME/.gtkrc-2.0>); but note the
B<--xde-theme> option as well.

=item B<--exec>, B<-e>

Execute the C<Exec=> action from the xsessions F<.desktop> file instead
of returning a string indicating the selected xsession.

(Note that the program actually executes C<xdg-launch -x I<SESSION>>
instead of determining how to execute the desktop file itself. See
L<xdg-launch(1)>.)

=item B<--xde-theme>, B<-x>

Use the current XDE desktop theme for the selection window instead of
the specified or default GTK theme.

=back

=head2 DEPRECATED OPTIONS

=over

=item B<--filename>

When a user session is selected, output the full path file name for the
X session desktop file instead of just the application id corresponding
to the file.  This is useful for passing the full file name to a session
manager such as L<xde-session(1)>.  In general, it is better to use the
B<--exec> option and specify the session manager in the X session
F<.desktop> file itself.  This option may mysteriously disappear at some
point.

=item B<--noask>, B<-n>

Do not ask the user whether she wishes to set the current session as the
default session when I<SESSION> is specified or chosen as something
different than the current default.

=item B<--charset>, B<-c> I<CHARSET>

Specify the character set with which to output the menu.  Defaults to
the character set in use by the current locale.
Because B<xde-chooser> is intended on running after the login, use of
this option is seldom necessary.
Just set the user locale properly in login scripts.

=item B<--language>, B<-l> I<LANGUAGE>

Specify the output language for the menu.  Defaults to the language set
in the current locale.
Because B<xde-chooser> is intended on running after the login, use of
this option is seldom necessary.
Just set the user locale properly in login scripts.

=back

=head2 GENERAL OPTIONS

=over

=item B<--dry-run>, B<-N>

Do not do anything (do not execute or write out files), just print to
standard error what would be done.  Implies a debug level of C<2>.

=item B<--debug>, B<-D> [I<LEVEL>]

Increment or set the debug level to I<LEVEL>.  The default debugging
level is C<0> (meaning no debugging).  When set, the program will print
debuggin information to standard error during operation.

(Note that because this option takes an optional argument, C<--> must be
specified before any non-option argument.)

=item B<--verbose>, B<-v> [I<LEVEL>]

Increment or set the output verbosity level to I<LEVEL>.  The default
output verbosity level is C<1>.

(Note that because this option takes an optional argument, C<--> must be
specified before any non-option argument.)

=back

=head1 USAGE

B<xde-chooser> can be run from an XDM to launch an X session, run as a
desktop application to switch a running X session, or run from the
command line to test its operation.  These three uses are detailed
below.

=head2 LAUNCHING AN X SESSION

B<xde-chooser> is meant to be called directly from an F<~/.xinitrc>
file, or from a display manager such as L<xde-xdm(1)> or L<slim(1)>.
It is normally not necessary to perform any initialization before
executing B<xde-chooser>.

=head2 SWITCHING X SESSIONS

B<xde-chooser> can be run as a desktop application to switch the
window manager currently being used (this is because L<xdg-launch> with
the B<-x> flag is capable of switching the running window manager in
many cases).  Simply run it with the B<--exec> option.  An application
F<.desktop> file is distributed with the release to provide a menu item
for this function of the program.

(Note that switching the window manager may fail when L<xdg-launch>
cannot determine how to stop a running window manager when the running
window manager does not conform to ICCCM 2.0 C<WM_S0> manager selection
semantics.)

=head2 TESTING OPERATION

B<xde-chooser> can also be run from the command line to check its operation
without having to be involved in an session or started by L<xinit(1)>.
The B<--dry-run> option is useful in combination with B<--exec> to keep
the chooser from attempting to execute the window manager.

=head1 CONFORMANCE

There are, in fact, no standards specifications for C<XSession> files.
There are many extensions added to the file format by various display
managers and session managers.

Display manager extensions tend to be focused on selecting an X session
coincident with login to an X display.  This is likely because the
classical GNOME2 L<gdm(1)> program allowed the user to select the X
session coincident with the login process.

Session manager extensions tend to be focused on the startup process for
the session, the capabilities of the window manager, and ongoing session
management capabilities of the combination of session manager with
window manager.

=head2 WINDOW MANAGERS

The I<XDE> suite (and B<xde-session> package) ships with a number of
session files that are contained in the F</usr/share/xde/xsessions>
directory.  The purpose of the B<xde-session> package has been to
support a wide range of light-weight window managers not specially
supported by any other session manager.  So, although B<xde-chooser> is
capable of launching a normal GNOME or KDE session, it might not be the
best way to do so.

The wide range of window managers supported by B<xde-chooser>, and for
which C<XSession> F<.desktop> files are shipped, are as follows:
L<2bwm(1)>,
L<adwm(1)>,
L<aewm(1)>,
L<aewm++(1)>,
L<AfterStep(1)>,
L<arch-meego(1)>,
L<awesome(1)>,
L<blackbox(1)>,
L<bspwm(1)>,
L<budgie-desktop(1)>,
L<cde(1)>,
L<cinamon(1)>,
L<compiz(1)>,
L<ctwm(1)>,
L<cwm(1)>,
L<deepin(1)>,
L<dwm(1)>,
L<e16(1)>,
L<echinus(1)>,
L<ede(1)>,
L<enlightenment(1)>,
L<etwm(1)>,
L<evilwm(1)>,
L<failsafewm(1)>,
L<fluxbox(1)>,
L<flwm(1)>,
L<fvwm(1)>,
L<glasswm(1)>,
L<gnome(1)>,
L<goomwwm(1)>,
L<herbstluftwm(1)>,
L<i3(1)>,
L<icewm(1)>,
L<jwm(1)>,
L<kodi(1)>,
L<larswm(1)>,
L<logram(1)>,
L<lxde(1)>,
L<lxqt(1)>,
L<lxsession(1)>,
L<mantis-wm(1)>,
L<mate(1)>,
L<matwm2(1)>,
L<mcwm(1)>,
L<metacity(1)>,
L<mutter(1)>,
L<mvwm(1)>,
L<mwm(1)>,
L<notion(1)>,
L<openbox(1)>,
L<pawm(1)>,
L<pekwm(1)>,
L<plan9port(1)>,
L<plasma(1)>,
L<qtile(1)>,
L<rio(1)>,
L<spectrwm(1)>,
L<ssh(1)>,
L<sugar(1)>,
L<trinity(1)>,
L<twm(1)>,
L<twobwm(1)>,
L<uwm(1)>,
L<velox(1)>,
L<vtwm(1)>,
L<waimea(1)>,
L<wind(1)>,
L<windowmaker(1)>,
L<windwm(1)>,
L<wm2(1)>,
L<wmaker(1)>,
L<wmii(1)>,
L<wmx(1)>,
L<xdwm(1)>,
L<xfce(1)>,
L<xmonad(1)>,
L<xsession(1)> and
L<yeahwm(1)>.

=head2 XSESSION DESKTOP ENTRIES

The C<XSession> files read by B<xde-chooser> are capable of
understanding various extensions to the desktop entry specification and
maintain compatibility to the extent possible with GNOME and KDE
extensions.  From these extensions B<xde-chooser> understands how to
launch a window manager on its own, within a lightweight session
manager, or within full blown session manager, whether that of XDE or
the GNOME or KDE session managers.

Instead of separate F<.desktop> files for each mode of launching the
window manager (within various sessions), B<xde-chooser> uses desktop
entry file actions to provide the mechanism for launching the window
manager in various ways.  An example C<XSession> file is as follows:

=head3 [Desktop Entry] Section

An example C<[Desktop Entry]> section from the F<adwm.desktop>
C<XSession> file is as follows:

    [Desktop Entry]
    Type=XSession
    Name=adwm
    GenericName=Window Manager
    GenericName[fr]=Gestionnaire de Fenêtres
    GenericName[pt]=Gestor de Janelas
    Comment=An advanced dynamic window manager for X
    Icon=adwm
    TryExec=/usr/bin/adwm
    Exec=adwm
    Terminal=false
    NoDisplay=true
    Categories=WindowManager;Application;System;
    StartupNotify=true
    X-GNOME-Autostart-Notify=true
    X-GNOME-Autostart-Phase=WindowManager
    X-GNOME-Provides=windowmanager
    X-GNOME-WMName=ADWM
    X-AppInstall-Package=adwm
    X-AppInstall-Popcon=0.00
    X-AppInstall-Section=aur
    X-Arch-Package=adwm 0.7.4-1
    X-Arch-Package-Repository=aur
    X-Arch-Package-Name=adwm
    X-Arch-Package-Version=0.7.4-1
    X-Arch-Package-Description=Advanced dynamic window manager for X
    X-Arch-Package-Groups=None
    X-Arch-Package-URL=http://github.com/bbidulock/adwm
    X-Arch-Package-Votes=3
    DesktopNames=ADWM
    X-LightDM-DesktopName=adwm
    Actions=XDE;

The fields are interpreted as follows:

=over

=item C<Type=XSession>

Provides the type of desktop entry file.  The only valid type in the
formal Desktop Entry specification is C<Application>; however,
C<XSession> is typically used for X sessions.  This field may be set to
C<Application> when the file is to also reside with other applications.
B<xde-chooser> will accept either C<XSession> or C<Application>.

=item C<Name=adwm>

The name of the desktop entry in accordance with specification.

=item C<GenericName=Window Manager>

=item C<GenericName[fr]=Gestionnaire de Fenêtres>

=item C<GenericName[pt]=Gestor de Janelas>

The generic name of the desktop entry in accordance with specification.
The generic name is often the same for all window managers and therefore
for all C<XSession> files.

=item C<Comment=An advanced dynamic window manager for X>

The description of the desktop entry in conformance with specification.

=item C<Icon=adwm>

The icon of the desktop entry in conformance with specification.  The
B<xde-icons> package provides a large number of light-weight window
manager icons, installed into XDG icon theme directories, that are not
normally shipped with, nor installed by most light-weight window
managers.

=item C<TryExec=/usr/bin/adwm>

The binary that must be available to use the desktop entry in
conformance with the XDG L<Desktop Entry Specification>.  This should
always be the binary executable of the window manager itself.  This
should normally use an absolute path.

=item C<Exec=adwm>

The command for the entry per specification.  This should be the command
necessary to start the window manager on its own (without a session).
The command should not use an absolute path.

=item C<Terminal=false>

Optional per specification: false when not provided.

=item C<NoDisplay=true>

Should be set to true.  This field is ignored by B<xde-chooser>, but
will be observed by XDG desktop entry programs such as menus and
launchers if the file is to also reside within an applications
directory.

=item C<Hidden=true>

Should be included an set to C<true> when the desktop entry is simply
used to occlude another C<XSession> entry in a lower priority XDG
directory.  B<xde-chooser> uses normal XDG search rules, so it is common
to set C<$XDG_CONFIG_DIRS=/etc/xdg/xde:/etc/xdg> and
C<$XDG_DATA_DIRS=/usr/local/share/xde:/usr/share/xde:/usr/local/share:/usr/share>
so that the shipped C<XSession> files are discovered first and the
undesirable ones that appear in F</usr/share/xsessions> can be occluded
by a file of the same name in F</usr/share/xde/xsessions> with
the C<Hidden> flag set to C<true>.

=item C<Categories=WindowManager;Application;System;>

Categories for window managers should always be set as above.

=item C<StartupNotify=true>

Specifies whether the window manager will perform desktop startup
notification completion in accordance with the
L<Desktop Startup Notification Specification>.  L<adwm(1)> does, so in
this case it is set to C<true>.  It is assumed that if a window manager
performs desktop startup notification for itself and indicates that it
supports C<_NET_STARTUP_ID>, C<_NET_STARTUP_INFO_BEGIN> and
C<_NET_STARTUP_INFO> in C<_NET_SUUPPORTED> that it also supports
assisting non-startup-notification-aware clients.

=item C<X-GNOME-Autostart-Notify=true>

=item C<X-GNOME-Autostart-Phase=WindowManager>

=item C<X-GNOME-Provides=windowmanager>

=item C<X-GNOME-WMName=ADWM>

=item C<X-AppInstall-Package=adwm>

=item C<X-AppInstall-Popcon=0.00>

=item C<X-AppInstall-Section=aur>

=item C<X-Arch-Package=adwm 0.7.4-1>

=item C<X-Arch-Package-Repository=aur>

=item C<X-Arch-Package-Name=adwm>

=item C<X-Arch-Package-Version=0.7.4-1>

=item C<X-Arch-Package-Description=Advanced dynamic window manager for X>

=item C<X-Arch-Package-Groups=None>

=item C<X-Arch-Package-URL=http://github.com/bbidulock/adwm>

=item C<X-Arch-Package-Votes=3>

=item C<DesktopNames=ADWM>

=item C<X-LightDM-DesktopName=adwm>

=item C<Actions=XDE;>

=back

Note that the C<OnlyShowIn> and C<NotShowIn> fields are pointless (as
the current desktop has not yet been set), and they should not appear in
the C<XSession> file.

=head3 [Window Manager] Section
    
    [Window Manager]
    Name=adwm
    SessionManaged=false
    StartupNotification=true
    X-XDE-Managed=true

=over

=item C<Name=adwm>

=item C<SessionManaged=false>

=item C<StartupNotification=true>

=item C<X-XDE-Managed=true>

=back

=head3 [Desktop Action ACTION] Section
    
    [Desktop Action XDE]
    Name=XDE
    Comment=adwm in an XDE session
    Icon=xde
    TryExec=/usr/bin/xde-session
    Exec=xde-session -desktop ADWM -startwm start-adwm
    DesktopNames=XDE:ADWM
    X-LightDM-DesktopName=xde

=over

=item C<[Desktop Action XDE]>

=item C<Name=XDE>

=item C<Comment=adwm in an XDE session>

=item C<Icon=xde>

=item C<TryExec=/usr/bin/xde-session>

=item C<Exec=xde-session -desktop ADWM -startwm start-adwm>

=item C<DesktopNames=XDE:ADWM>

=item C<X-LightDM-DesktopName=xde>

=back

=head1 FILES

=over

=item F<$HOME/.dmrc>

This file contains the default session in the C<Session=> key of the
C<[Desktop]> section.  This file will be written whenever a new
default is chosen.  It will be read in preference to the
F<$XDG_CONFIG_HOME/xde/default> file.

=item F<$XDG_CONFIG_HOME/xde/default>

This file contains the default session.  The file consists of a single
line containing the session name.
Remember that the session name is the name of the F<.desktop> file
without the C<.desktop> suffix.

=item F<$XDG_CONFIG_HOME/xde/current>

This file contains the current session.  The file consists of a single
line containing the session name.
Remember that the session name is the name of the F<.desktop> file
without the C<.desktop> suffix.

=item F<@XDG_DATA_DIRS/xsessions/*.desktop>

These locations are searched for F<.desktop> files that describe which X
Sessions are to be made available to the user.  Files in this directory
can be desktop files of type B<Application> or B<XSession>.  A B<Window
Manager> section may also describe whether the session needs to be
managed or whether the window manager is capable of managing its own
session.  Desktop entry files in data directories earlier in the search
path override desktop entry files of the same filename later in the
search path.

The I<XDE> suite ships with a number of F<*.desktop> files that are
installed into the F</usr/share/xde/xsessions> directory and are used to
override those for I<gdm> that are normally contained in
F</usr/share/xsessions>.  (To do this, B<xde-chooser> prepends the path
F</usr/share/xde> to the B<XDG_DATA_DIRS> environment variable.)

For a set of these window managers, B<xde-chooser> will execute
L<xde-startup(1)> with the session as an argument.  See
L<xde-startup(1)/WINDOW MANAGERS> for a list of supported window
managers.

=back

=head1 ENVIRONMENT

The following environment variables (in alphabetical order) are examined
or set by B<xde-chooser>:

=over

=item B<DESKTOP_SESSION>

To emulate L<lxsession(1)>, the C<DESKTOP_SESSION> environment variable
is set to the value that resulted from option and environment variable
processing for children of the session.

=item B<DESKTOP_STARTUP_ID>

B<xde-chooser> is a GTK program and has been configured to automatically
perform startup notification completion on startup (not that anyone is
listening at this point).

=item B<DISPLAY>

Used to determine X Display.  When the B<--display> option is specified,
this environment variable will be set to the specified value.

=item B<FBXDG_DE>

To emulate L<fbautostart>, the C<FBXDG_DE> environment variable is
examined when the C<--desktop> option is not specified and the
C<XDG_CURRENT_DESKTOP> environment variable is not set.  C<FBXDG_DE> is
set to the value that resulted from option and environment variable
processing for children of the session.

=item B<HOME>

Will be used to determine the user's home directory for the purpose of
calculating the default value for C<XDG_CONFIG_HOME> and
C<XDG_DATA_HOME> when required.  When unspecified, the home directory
for the current local user is determined from the password file.
Failing that, the current directory is used.

=item B<HOSTNAME>

Will be used to determine the local host name.  When unspecified, the
name will be determined from the L<gethostname(3)> call.  This value is
used to determine the host for which to save session files.  Also, will
be used to determine the default directory for some configuration and
commands.

=item B<LANG>

Used to set the current locale.

=item B<_LXSESSION_PID>

To emulate L<lxsession(1)>, the C<_LXSESSION_PID> environment variable
is set to the PID of B<xde-session>, the process group leader responsible
for launching all tasks under the X session manager.  The X session can
be terminated by killing this process.

=item B<USER>

Will be used to determine the name of the local user.  When unspecified,
the user name for the current pid will be determined from the password
file and this environment variable will be set.  Failing that it will
not be set.

=item B<XDG_CONFIG_DIRS>

Specifies the system XDG configuration directory.  When unspecified,
defaults to F</etc/xdg> in accordance with XDG specifications.
The directory F</etc/xdg/xde> will be prefixed to the path unless the
directory is already a component of the path.
B<xde-chooser> uses these directories to determine the list of default
configuration directories to search.

=item B<XDG_CONFIG_HOME>

Specifies the user XDG configuration directory.  When unspecified,
defaults to F<$HOME/.config> in accordance with XDG specifications.
B<xde-chooser> uses this directory to determine the list of default
configuration directories to search.  The subdirectory
F<$XDG_CONFIG_HOME/autostart> will be examined for F<*.desktop> files.

=item B<XDG_CURRENT_DESKTOP>

When the C<--desktop> option is not specified, C<XDG_CURRENT_DESKTOP> is
examined to determine the current desktop.  C<XDG_CURRENT DESKTOP> is
set to the value that resulted from option and environment variable
processing for children of the session.

=item B<XDG_DATA_DIRS>

Specifies the system XDG data directories.  When unspecified, defaults
to F</usr/local/share:/usr/share> in accordance with XDG specifications.
The directory F</usr/share/xde> will be prefixed to the path unless the
directory is already a component of the path.
B<xde-chooser> uses these directories to determine the list of default
data directories to search.

=item B<XDG_DATA_HOME>

Specifies the user XDG data directory.  When unspecified, defaults to
F<$HOME/.local/share> in accordance with XDG specifications.
B<xde-chooser> uses this directory to determine the list of default data
directories to search.  The subdirectory F<$XDG_DATA_HOME/xsessions>
will be examined for F<*.desktop> files.

=item B<XDG_MENU_PREFIX>

This variable has no default.  If the variable is not set when the
B<xde-session> program is executed, it sets it to the specified or
default B<--vendor> option followed by a dash (C<->).  This variable
determines which files are used to construct XDG menus.

When the B<--wmname> option is specified and the B<--desktop> option is
not specified, C<$XDG_CURRENT_DESKTOP> is set to the window manager name
folded to all uppercase.

=item B<XDG_SESSION_PID>

C<XDG_SESSION_PID> is set to the PID of B<xde-session>, the process group
leader responsible for launching all tasks under the X session manager.
The X session can be terminated by killing this process.  See also
L</SIGNALS>, below.

=item B<XDG_VENDOR_ID>

This environment variable is examined to determine the default for the
B<--vendor> option.  When the B<--vendor> option is specified or
defaults, this environment variable is set to the value that results
from option and environment variable processing.  This is a convenience
for when the B<--vendor> option cannot be derived from the
C<XDG_MENU_PREFIX> environment variable.  It is not an XDG standard
environment variable.

=back

=head1 BUGS

B<xde-chooser> should really output the path to the F<XSessions> file
instead of the lowercase session name.

Please report bugs for current versions to the source code repository at
L<https://github.com/bbidulock/xde-session/issues>.

=head1 HISTORY

I wrote B<xde-chooser> to provide a mechanism for selecting available
window managers in an XDG compliant way for the I<unexicon> desktop.
With L<gdm(1)> going to GTK3, the I<unexicon> desktop uses L<xdm(8)>,
L<slim(1)>, L<xde-chooser(1)> and L<xde-session(1)> instead.

B<xde-chooser> was originally written as a gtk-perl program;
however, I hate to wait on computers so it was converted to C<C>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

See B<--copying> for full copyright notice and copying permissions.

=head1 SEE ALSO

L<getopt_long_only(3)>, L<xde-logout(1)>, L<xde-session(1)>,
L<xde-startup(1)>, L<xdg-launch(1)>, L<lxsession-logout(1)>,
L<lxsession(1)>.

=head1 LICENSE

See the F<COPYING> file in the distribution or use the B<--copying> flag
to display copying permissions.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
