=pod

=head1 NAME

 xde-session - start a window-manager session

=head1 SYNOPSIS

 xde-session [ COMMAND ] [ OPTIONS ] [ SESSION ]
 xde-session --help

 xde-session help
 xde-session edit    [ OPTIONS ]
 xde-session run     [ OPTIONS ] COMMAND ARG ...
 xde-session start   [ OPTIONS ] [ SESSION ]
 xde-session restart [ OPTIONS ] [ SESSION ]

=head1 DESCRIPTION

B<xde-session> starts a new X session, optionally launches a window
manager, and optionally starts any additional applications or XDG
auto-start applications as specified by the I<XDG Desktop Specification>. 

See the L</USAGE> section for usage examples.

=head1 COMMANDS

Command options that control the major behaviour of B<xde-session> are as
follows:

=over

=item B<--help>, B<help>

Print a brief usage message to stdout and then exit.

=item B<--test>, B<test>

Regardless of the other options, do not launch any tasks or perform any
other actions that would conflict with another running B<xde-session>.
Also, do not guarantee that the running B<xde-session> is unique for the
display.  This is for testing, to see visually what B<xde-session> would
do and to allow for the testing and development of the task monitor and
session editor.

=item B<--edit>, B<-m>, B<edit>

Invoke the session editor dialog on the running lxsession (or a new
editor when B<--test> is specified or no xde-session is running).

Most of the command line options are intended for use by X
initialization scripts (such as those in L<xmd(1)>) that invoke the X
session.  Many additional options are available only through the
configuration file or the editor.

=item B<--run>, B<-u>, B<exec>

Ask a running B<xde-session> instance to launch and manage a program

=item B<--restart>, B<-r>

=back

=head1 ARGUMENTS

=over

=item I<SESSION>

B<xde-session> only recognizes a single optional non-option argument,
I<SESSION>.  When specified this argument has the same effect as the
B<--session> argument and overrides the setting of both the B<--session>
argument, the B<XDG_CURRENT_DESKTOP> and the B<DESKTOP_SESSION>
environment variables.

=back

=head1 OPTIONS

The program uses L<getopt_long_only(3)> to parse options, so abbreviated
or single-dash long options are recognized when not ambiguous.  The
program accepts the following options:

=head2 COMMAND OPTIONS

The following command options are mutually exclusive: the first option
in this group sets the mode of the program.  When no command option is
specified, the program assumes normal operation.  In normal operation,
session selection and startup begins.

=over

=item B<--help>, B<-h>

Print usage information to standard error containing current option
settings and exit.

=item B<--version>, B<-V>

Print the program version to standard output and exit.

=item B<--copying>, B<-C>

Print copying permissions to standard output and exit.

=back

=head2 GENERAL OPTIONS

The following general options can be used with most of the command
options listed above:

=over

=item B<--display> I<DISPLAY>

Specifies the display to use.  This is not normally necessary as the
display is obtained from the B<DISPLAY> environment variable when this
option is not specified.

=item B<--desktop>, B<-e> I<DESKTOP>

Specify the desktop environment (DE) to use, I<DESKTOP>, e.g.  C<ADWM>,
C<BLACKBOX>, C<ICEWM>, C<FLUXBOX>.  The default value when not specified
is C<XDE>.  The desktop environment must be specified when
B<--autostart> is specified.

In L<lxsession(1)> compatibility mode, this is equivalent to the B<-e>
option to L<lxsession(1)>.  This option may also be specified using the
B<XDG_CURRENT_DESKTOP> or B<FBXDG_DE> environment variables described
below.

=item B<--session>, B<-s> I<SESSION>

Invokes L<lxsession(1)> compatibility mode, and specifies the session
profile to use for emulating L<lxsession(1)>.  This is equivalent to the
B<-s> option to L<lxsession(1)>.  This option may also be specified
using the B<DESKTOP_SESSION> environment variable as described below.

=item B<--startwm>, B<-m> I<EXECUTE>

Execute the command string, I<EXECUTE>, to start a window manager.
Shell characters will be interpreted.  When specified, the window
manager will be started before all other tasks.

When not specified, this option will be determined from the
L<session.conf> file in the F<SESSION> subdirectory under
F<$XDG_CONFIG_HOME/xde-session>, where F<SESSION> is specified by the
B<-s> option, or by the first non-option argument.

In L<lxsession(1)> compatibility mode, this option will be determined
from the L<lxsession(1)> F<desktop.conf> file in the F<SESSION>
subdirectory under F<$XDG_CONFIG_HOME/lxsession>, where F<SESSION> is
specified with the B<-s> option.

=item B<--wmname> I<WNAME>

Specifies the name of the window manager executable.

When setting up the session, unless the B<--setup> option is specified,
this name is used to look in config directories for an executable file
named
F<$XDG_CONFIG_HOME:$XDG_CONFIG_DIRS/$WMNAME/setup.sh>.  If one exists
and is executable, it is run as the setup script.

When starting the window manager, unless the B<--startwm> option is
specified, this name is used to look in config directories for an
executable file named
F<$XDG_CONFIG_HOME:$XDG_CONFIG_DIRS/$WMNAME/start.sh>.  If one exists
and is executable, it is run instead of the window manager.  If the
start shell script does not exist or is not executable, $WMNAME, is
simply executed with no arguments.  If you wish to pass arguments to the
program, use the B<--startwm> option.

If the B<--wmname> option is specified and no B<--desktop> or
B<-ssession> option is provided, the desktop and session default to the
I<WMNAME> folded to all uppercase.  When no B<--wmname> option is
specified, it defaults to the desktop or session folded to all
lowercase.

=item B<--file>, B<-f> I<FILE>

Execute the commands contained in the file, I<FILE>, after executing the
window manager, but before executing any other commands or auto-starting
tasks.  File is compatible with the L<lxsession(1)> F<autostart> file.
Each line of the file contains a shell command to execute, optionally
prefixed with a C<@> to indicate that the process should be restarted
when it exits abnormally.  Tasks executed from this file will be started
before any specified by the B<-x> option, or auto-started from XDG
autostart desktop files.

In L<lxsession(1)> compatibility mode, this option will default to the
F<autostart> file in the F<SESSION> subdirectory under
F<$XDG_CONFIG_HOME/lxsession>, where F<SESSION> is specified with the
B<-s> option.

=item B<--setup> I<COMMAND>

Execute the command string, I<COMMAND>, to setup the window manager
before it is invoked.  This option defaults to executing the shell setup
program in F<$XDG_CONFIG_{HOME,DIRS}/\LDESKTOP\E/setup.sh> if such a shell
exists.  The option may be repeated to execute a number of commands in the
order specified.  These commands are executed in the foreground, one after
the other, before the window manager or any other task is started.  The
session will die if any of these commands exit with a non-zero exit status
or terminate on a signal.

This option can be repeated and the commands will be executed in order.

=item B<--exec>, B<-x> I<COMMAND>

Execute the command string, I<COMMAND>, to start applications after the
window manager, and before autostart tasks are executed.  This option
defaults to none.  The option may be repeated to execute a number of
commands the order specified.  It is possible to prefix the I<COMMAND>
string with a single C<@> that will indicate that the task should be
restarted when it exits abnormally.

This option can be repeated and the commands will be executed in order.

=item B<--autostart>, B<--noautostart>, B<-a>

Specifies whether (or not) to autostart XDG applications in accordance
with the I<Desktop Application Autostart Specification>.  The inverted
sense of the B<-a> flag is for compatibility with L<lxsession(1)>.

=item B<--wait>, B<-w>, B<--nowait>

Specifies whether (or not) to wait for a window manager to take control
of the root window of the default screen of the display before starting
further applications.  This option takes effect regardless of whether
the B<--startwm> option has been specified.

=item B<--pause>, B<-p> [I<PAUSE>]

Specifies the interval of time, I<PAUSE>, in seconds to wait after the
window manager initialization phase before starting the first
applications.  If I<PAUSE> is not specified, it defaults to 2 seconds.
The default when the option is not specified is not to pause at all.
The pause can be explicitly disable by using a I<PAUSE> value of zero
(0).

=item B<--splash>, B<-l> [I<IMAGE>]

Specifies that a splash window is to be generated and optionally
populated with an image from the file, I<IMAGE>, (that can be in XPM or
PNG format).  The splash window will display the icons of the XDG
compliant F<*.desktop> files as they are started.  The I<IMAGE> is for
optional branding.

=item B<--vendor>, B<-v> I<VENDOR>

Specifies the vendor name for branding and custom configuration.  The
default when unspecified is C<unexicon>.  Use a null string to defeat
branding.  Specifying or defaulting I<VENDOR> causes F</etc/xdg/$VENDOR>
to be prefixed to C<$XDG_CONFIG_DIRS> and F</usr/share/$VENDOR> to be
prefixed to C<$XDG_DATA_DIRS>.

Also, if the C<$XDG_MENU_PREFIX> environment variable is not set up, it
will be set to I<VENDOR> with a C<-> appended.

(Note that, regardless of vendor setting, F</etc/xdg/xde> is always
prefixed to C<$XDG_CONFIG_DIRS> and F</usr/share/xde> is always prefixed
to C<$XDG_DATA_DIRS>.)

=item B<--mkdirs>, B<--nomkdirs>

Make (or not) missing user directories.  User directories that will be
created are F<$HOME/Desktop>, F<$HOME/Downloads>, F<$HOME/Templates>,
F<$HOME/Public>, F<$HOME/Documents>, F<$HOME/Documents/Music>,
F<$HOME/Documents/Pictures>, F<$HOME/Documents/Videos>.

(Note that, on Arch Linux, user directories are normally updated by the
F<xdg-user-dirs-update> L<systemd(8)> service.)

=item B<--toolwait>, B<W> [I<GUARD>][:I<DELAY>]

When auto-starting tasks for which startup notification completion can be
determined, serialize the startup in a similar fashion to
L<xtoolwait(1)>, where the next autostart task is not launched until the
previous task is complete, or the guard timeout period, I<GUARD>, in
milliseconds, expires.  Where startup notification completion cannot be
determined (such as for command executed from the B<--file> or B<--exec>
options), the program will wait I<DELAY> milliseconds before starting the
next task.  I<GUARD> defaults to 200 milliseconds.  I<DELAY> defaults to
zero (0) milliseconds.  The default is to perform tool wait.  To disable
tool wait, specify C<--toolwait 0:0>.

=item B<--charset>, B<-c> I<CHARSET>

Specify the character set with which to output the XDG desktop file
derived information.  Defaults to the character set (LC_CHARSET) in use
by the current locale.  Because the program is intended on running after
login, use of this option is seldom necessary.

=item B<--language>, B<-L> I<LANGUAGE>

Specify the output language for XDG desktop file derived information.
Defaults to the language (LC_MESSAGES) of the current locale.  Because
the program is intended on running after login, use of this option is
seldom necessary.

=item B<--banner>, B<-b> I<BANNER>

Specifies a custom splash login logo.  When unspecified, the program
will use a branded logo that depends on environment variables.  This
option is compatible with other tools and is an alternate way of
specifying the I<IMAGE> argument to the B<--splash> option.

=item B<--message>, B<-g> I<MESSAGE>

=item B<--side>, B<-s> {B<left>|B<top>|B<right>|B<bottom>}

Specifies the side of the window on which the logo will be placed.  This
option is recognized for compatibility with L<lxsession-logout(1)>.
B<xde-logout> always places the logo on the left and this option is
ignored.

=item B<--icons>, B<-i> I<THEME>

Specifies the icon theme to use.  Otherwise, the user's default GTK+
icon theme will be used (i.e. from F<$HOME/.gtkrc-2.0>; but note the
B<--xde-theme> option as well.

=item B<--theme>, B<-t> I<THEME>

Specifes the GTK+ theme to use.  Otherwise, the user's default GTK+
theme will be used (i.e. from F<$HOME/.gtkrc-2.0>); but note the
B<--xde-theme> option as well.

=item B<--xde-theme>, B<-X>

Use the current XDE desktop theme for the splash window instead of the
specified or default GTK+ theme.

=item B<--foreground>, B<-F>

The default is for the program to daemonize itself and continue
monitoring auto-started tasks in the background.  This option causes the
program to run in the foreground and prints debugging information to
standard error.  Implies a debug level of 2.

=item B<--foreground>, B<-F>

The default is for the program to daemonize itself and continue
monitoring auto-started tasks in the background.  This option causes the
program to run in the foreground and prints debugging information to
standard error.  Implies a debug level of 2.

=item B<--dry-run>, B<-n>

Do not do anything (do not execute or write out files), just print to
standard error what would be done.  Implies a debug level of 2.  Useful
with B<--foreground>.

=item B<--debug>, B<-d> [I<LEVEL>]

Increment or set the debug level to I<LEVEL>.  The default debugging
level is 0 (meaning no debugging).  When set, the program will print
debugging information to standard error during operation.

(Note that because this option takes an optional argument, C<--> must be
specified before any non-option argument.)

=item B<--verbose>, B<-v> [I<LEVEL>]

Increment or set the output verbosity level to I<LEVEL>.  THe default
output verbosity level is 1.

(Note that because this option takes an optional argument, C<--> must be
specified before any non-option argument.)

=back

=head1 USAGE

When used directly, B<xde-session> will launch the following window
managers and include a setup program that will establish the correct
environment for the window manager, and provide default window manager
configuration files located in the
F<$XDG_RUNTIME_DIR/$XDG_CURRENT_DESKTOP> subdirectory:

=over

=item B<ADWM>

Where you would invoke L<adwm(1)>, invoke one of the following:

 XDG_CURRENT_DESKTOP=ADWM xde-session
 xde-session -desktop ADWM

=item B<BLACKBOX>

Where you would invoke L<blackbox(1)>, invoke one of the following:

 XDG_CURRENT_DESKTOP=BLACKBOX xde-session
 xde-session -desktop BLACKBOX

=item B<CTWM>

Where you would invoke L<ctwm(1)>, invoke one of the following:

 XDG_CURRENT_DESKTOP=CTWM xde-session
 xde-session -desktop CTWM

=item B<ETWM>

Where you would invoke L<etwm(1)>, invoke one of the following:

 XDG_CURRENT_DESKTOP=ETWM xde-session
 xde-session -desktop ETWM

=item B<FLUXBOX>

Simply execute B<xde-session> as the only command in your
F<~/.fluxbox/startup> file.  The execution line should look like:

 xde-session --desktop FLUXBOX --startwm "fluxbox -rc ~/.fluxbox/init"

where F<~/.fluxbox/init> is just the default.  Use B<xde-session-edit(1)>
to auto-start the programs that you would otherwise start from your
F<startup> script.  Therefore the above command bypasses the normal
F<startup> script, which is likely unaware of B<xde-session>.

=item B<FVWM>

L<fvwm(1)> does not yet have a setup program.

=item B<ICEWM>

L<icewm(1)> user normally either launch L<icewm(1)> alone or
L<icewm-session(1)>.  L<icewm-session(1)> provides some limited
auto-starting of applications (it forks L<icewwmtray(1)> and
L<icewmbg(1)> as well as L<icewm(1)> itself), but does not support XDG
Autostart, XSETTINGS and Startup Notification.

To use L<icewm-session(1)> execute:

 xde-session -desktop ICEWM -startwm icewm-session

To use L<icewm(1)> on its own, execute:

 xde-session -desktop ICEWM -startwm icewm

=item B<JWM>

=item B<LXDE>

L<lxde(1)> does not yet have a setup program.

=item B<METACITY>

L<metacity(1)> does not yet have a setup program.

=item B<OPENBOX>

L<openbox(1)> is typically started either using L<openbox-session(1)>
directly, or under LXDE using L<lxdestart(1)>.

=item B<PEKWM>

=item B<TWM>

=item B<UWM>

L<uwm(1)> does not yet have a setup program; however, configuration
files exist for this window manager.

 xde-session -desktop UWM -startwm uwm

=item B<VTWM>

=item B<WAIMEA>

=item B<WMAKER>

L<wmaker(1)> does not yet have a setup program.

L<wmaker(1)> has its own non-XDG compliant session management.  This
means that if B<xde-session> is used to launch WindowMaker, it should be
made to suppress XDG auto-start tasks using the B<--noautostart> or B<-a>
option, such as:

 xde-session --noautostart --desktop WMAKER --startwm wmaker

=back

When used directly, B<xde-session> will launch the following window
managers (and likely others as a variation on a theme) successfully:

=over

=item B<AFTERSTEP>

 xde-session -desktop AFTERSTEP -startwm afterstep

=item B<MUTTER>

 xde-session -desktop MUTTER -startwm afterstep

L<mutter(1)> has no menus or hot keys so you should start an L<xterm(1)>
in the background before executing B<xde-session>.

=item B<VELOX>

 xde-session -desktop VELOX -startwm velox

L<velox(1)> has no menus or hot keys so you should start an L<xterm(1)>
in the background before executing B<xde-session>.

=item B<I3>

 xde-session -desktop I3 -startwm i3

L<i3(1)> has no menus or hot keys so you should start an L<xterm(1)>
in the background before executing B<xde-session>.

=item B<MWM>

=item B<AWESOME>

=item B<FVWM>

=item B<METACITY>

=item B<CWM>

=item B<BSPWM>

=item B<2BWM>

=item B<ECHINUS>

=item B<AEWM>

=item B<YEAHWM>

=item B<HERBSTLUFTWM>

=item B<MATWM2>

=item B<FLWM>

=item B<WMX>

=item B<VTWM>

=item B<LARSWM>

=back

B<xde-session> provides F<.desktop> files for, and can successfully
launch, the following X sessions:
L<2bwm(1)>, L<adwm(1)>, L<aewm(1)>, L<afterstep(1)>, L<arch-meego(1)>,
L<awesome(1)>, L<blackbox(1)>, L<bspwm(1)>, L<compiz(1)>, L<ctwm(1)>,
L<cwm(1)>, L<dwm(1)>, L<echinus(1)>, L<ede(1)>, L<enlightenment(1)>,
L<evilwm(1)>, L<failsafewm(1)>, L<fluxbox(1)>, L<flwm(1)>, L<fvwm(1)>,
L<gnome(1)>, L<goomwwm(1)>, L<herbstluftwm(1)>, L<i3(1)>, L<icewm(1)>,
L<jwm(1)>, L<larswm(1)>, L<logram(1)>, L<lxde(1)>, L<mantis(1)>,
L<mate(1)>, L<matwm2(1)>, L<mcwm(1)>, L<metacity(1)>, L<mutter(1)>,
L<mvwm(1)>, L<mwm(1)>, L<openbox(1)>, L<pawm(1)>, L<pekwm(1)>,
L<rio(1)>, L<spectrwm(1)>, L<trinity(1)>, L<twm(1)>, L<twobm(1)>,
L<uwm(1)>, L<velox(1)>, L<vtwm(1)>, L<waimea(1)>, L<wind(1)>,
L<wmaker(1)>, L<wm2(1)>, L<wmii(1)>, L<wmx(1)>, L<xdwm(1)>, L<xfce(1)>,
L<xmonad(1)>, L<YEAHWM(1)>.

=head1 EXAMPLES

=head1 FILES

=over

=item F<$XDG_CONFIG_{HOME,DIRS}/lxsession/SESSION/autostart>

The default F<autostart> files in L<lxsession(1)> compatibility mode.
Note that the values from B<all> auto-start files will be used.

=item F<$XDG_CONFIG_{HOME,DIRS}/lxsession/SESSION/desktop.conf>

The default F<desktop.conf> file in L<lxsession(1)> compatibility mode.
Note that the values from only the file in the "most important"
directory will be used.

=back

=head1 ENVIRONMENT

The following environment variables are examined or set by B<xde-session>:

=over

=item B<DISPLAY>

Used to determine X Display.  When the B<--display> option is specified,
this environment variable will be set to the specified value.

=item B<HOME>

Will be used to determine the user's home directory for the purpose of
calculating the default value for C<XDG_CONFIG_HOME> and
C<XDG_DATA_HOME> when required.  When unspecified, the home directory
for the current local user is determined from the password file.
Failing that, the current directory is used.

=item B<HOSTNAME>

Will be used to determine the local host name.  When unspecified, the
name will be determined from the L<gethostname(3)> call.  This value is
used to determine the host for which to save session files.  Also, will
be used to determine the default directory for some configuration and
commands.

=item B<LANG>

Used to set the current locale.

=item B<USER>

Will be used to determine the name of the local user.  When unspecified,
the user name for the current pid will be determined from the password
file and this environment variable will be set.  Failing that it will
not be set.

=item B<XDG_CONFIG_HOME>

When set, C<$XDG_CONFIG_HOME/autostart> will be examined for
C<*.desktop> files.  The variable defaults to C<$HOME/.config>.

=item B<XDG_CONFIG_DIRS>

When set, C<DIRECTORY/autostart> will be examined for each C<DIRECTORY>
in the colon separated list of directories contained in
C<XDG_CONFIG_DIRS>.  The variable defaults to F</etc/xdg>.  When the
B<--vendor> option is specified, or defaults, F</etc/xdg/$VENDOR> is
prefixed to the normal default.  F</etc/xdg/xde> will always be prefixed
to the result.

=item B<XDG_CURRENT_DESKTOP>

When the C<--desktop> option is not specified, C<XDG_CURRENT_DESKTOP> is
examined to determine the current desktop.  C<XDG_CURRENT DESKTOP> is
set to the value that resulted from option and environment variable
processing for children of the session.

=item B<XDG_DATA_HOME>

The variable defaults to F<$HOME/.local/share>.

=item B<XDG_DATA_DIRS>

The variable defaults to F</usr/local/share:/usr/share>.  When the
B<--vendor> option is specified, or defaults, F</usr/share/$VENDOR> is
prefixed to the normal default.  F</usr/share/xde> will always be
prefixed to the result.

=item B<XDG_MENU_PREFIX>

This variable has no default.  If the variable is not set when the
B<xde-session> program is executed, it sets it to the specified or
default B<--vendor> option followed by a dash (C<->).  This variable
determines which files are used to construct XDG menus.

When the B<--wmname> option is specified and the B<--desktop> option is
not specified, C<$XDG_CURRENT_DESKTOP> is set to the window manager name
folded to all uppercase.

=item B<FBXDG_DE>

To emulate L<fbautostart>, the C<FBXDG_DE> environment variable is
examined when the C<--desktop> option is not specified and the
C<XDG_CURRENT_DESKTOP> environment variable is not set.  C<FBXDG_DE> is
set to the value that resulted from option and environment variable
processing for children of the session.

=item B<DESKTOP_SESSION>

To emulate L<lxsession(1)>, the C<DESKTOP_SESSION> environment variable
is set to the value that resulted from option and environment variable
processing for children of the session.

=item B<XDG_SESSION_PID>

C<XDG_SESSION_PID> is set to the PID of B<xde-session>, the process group
leader responsible for launching all tasks under the X session manager.
The X session can be terminated by killing this process.

=item B<_LXSESSION_PID>

To emulate L<lxsession(1)>, the C<_LXSESSION_PID> environment variable
is set to the PID of B<xde-session>, the process group leader responsible
for launching all tasks under the X session manager.  The X session can
be terminated by killing this process.

=back

=head1 SIGNALS

=over

=item I<SIGTERM>

A I<SIGTERM> signal sent to the C<$XDG_SESSION_PID> or
C<$_LXSESSION_PID> will terminate the entire session.  This should be
avoided when the window manager does not properly catch termination
signals and save its configuration before terminating.

When the B<--startwm> option is specified or implied, B<xde-session> will
also terminate when the window manager exits normally.

=back

=head1 CAVEATS

When in L<lxsession(1)> compatibility mode, B<xde-session> cannot act as
an Xsettings daemon in accordance with the Xsettings specification.
L<lxsession(1)> can.

=head1 BUGS

B<xde-sessions> had no known bugs at the time of release.  Please report
bugs for current versions to the source code repository at
L<https://github.com/bbidulock/xde-session/issues>.

=head1 HISTORY

I wrote B<xde-session> due to the deficiencies of B<fbautostart(1)> and
L<lxsession(1)> when launching XDG-compliant applications and desktop
environments over NWM/ENWM compliant light-weight window managers.  The
program was originally written in C<perl>, but later ported to C<C>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

See B<--copying> for full copyright notice and copying permissions.

=head1 SEE ALSO

L<lxsession(1)>, L<Standards(7)>,
L<Basedir|http://www.freedesktop.org/wiki/Specifications/basedir-spec>,
L<Desktop Entry Specification|http://www.freedesktop.org/wiki/Specifications/desktop-entry-spec>,
L<Desktop Application Autostart Specification|http://www.freedesktop.org/wiki/Specifications/autostart-spec>,
L<Desktop Menu Specification|http://www.freedesktop.org/wiki/Specifications/menu-spec>,
L<Startup Notification|http://www.freedesktop.org/wiki/Specifications/startup-notification-spec>,
L<XSETTINGS|http://www.freedesktop.org/wiki/Specifications/xsettings-spec>,
L<System Tray|http://www.freedesktop.org/wiki/Specifications/systemtray-spec>.

=head1 LICENSE

See the F<COPYING> file in the distribution or use the B<--copying> flag
to display copying permissions.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
