=pod

=head1 NAME

xde-xchooser - A GTK2 XDMCP Host chooser replacement.

=head1 SYNOPSIS

B</usr/lib/X11/xdm/xde-xchooser> [I<OPTIONS>] ADDRESSES ...

=head1 DESCRIPTION

B<xde-xchooser> is a GTK2 replacement for the horribly ugly Athena
Widget Set chooser that comes with Xorg X Display Manager.
It is designed to let L<xdm(1)> do the heavy lifting of coordinating the
majority of the XDMCP protocol while providing a more aesthetic
appearance.

=head1 ARGUMENTS

=over 4

=item I<ADDRESSES ...>

Provides the human-readable (decimal and dot notation, host names)
specification of the display managers to query to determine whether they
are willing to manage a display.  In addition to all manner of textual
IP addresses, the special value C<BROADCAST> can be specified to indicate
to the chooser that it should (also) broadcast queries to discover
display managers.  The special value C<DNS-SD> can be specified to
indicate to the chooser that it should (also) use C<DNS-SD> to discover
display managers that offer the C<tcp.xdmcp> service.  The special
value C<MULTICAST> can be specified to indicate to the chooser that it
should (also) use multicast to discover display managers.

=back

=head1 OPTIONS

No options are necessary.  When launched by L<xdm(1)>, it will provide
the appropriate arguments.  B<xde-xchooser> can be launched directly on
the command line of an x-terminal to test its appearance and operation.
In this mode, arguments are still required but no options.  Absence of
the B<-xdmAddress>, B<-clientAddress> and B<-connectionType> options
indicates to B<xde-xchooser> that it was not launched by L<xdm(1)> or an
L<xdm(1)> work-alike as a chooser.  See L</USAGE> for more information.

=head2 COMMAND OPTIONS

When no command option is specified, B<xde-xchooser> executes the program.
The following command options, when specified, print information instead
of running the program.

=over 4

=item B<-help>

Instead of operating normally, the program prints usage information to
standard output and exits.

=item B<-version>

Instead of operating normally, the program prints detailed version
information and exits.

=item B<-copying>

Instead of operating normally, the program prints detailed copying
permissions and exits.

=back

=head2 XDM OPTIONS

XDM options are not normally specified by the user of the program on the
command line: they are, instead, provided by L<xdm(1)> when
B<xde-xchooser> is being used as a greeter program.

=over 4

=item B<-xdmAddress> I<ADDRESS>

Specifies the address of a TCP socket upon which L<xdm(1)> is awaiting
instructions for the server.  L<xdm(1)> encodes this I<ADDRESS> as a
string of hexadecimal characters (with no 0x prefix) representing the
binary socket address.  The first two bytes are a host-byte-order 16-bit
address family (e.g. AF_INET); the second and third bytes are the
host-byte-order 16-bit port number; and the remaining 4 or 16 bytes are
the IPv4 or IPv6 network-byte-order IP address.

B<xde-xchooser> uses the socket address communicated in this option to
communicate the selection back to L<xdm(1)>.

=item B<-clientAddress> I<IPADDR>

Specifies the client IP address I<IPADDR> that initiated the request.
L<xdm(1)> encodes this as a string of hexadecimal characters (with no 0x
prefix) representing the 4- or 16-byte IPv4 or IPv6 network-byte-order
IP address.

B<xde-xchooser> uses this option to identify the originating client back
to L<xdm(1)> when a selection is made.

=item B<-connectionType> I<TYPE>

Specifies the connection type supported by the client as a decimal
number, I<TYPE>.

B<xde-xchooser> uses this option to filter the list of willing display
managers to those that support this connection type.  The three types of
interest to L<xdm(1)> (see F</usr/include/X11/Xdmcp.h>) are:

=over 4

=item 0 - B<FamilyInternet> (AF_INET addresses only)

=item 6 - B<FamilyInternet6> (AF_INET6 addresses only)

=item 256 - B<FamilyLocal> (AF_UNIX addresses only)

=back

L<xdm(1)> will only supply B<FamilyInternet>(0) or B<FamilyInternet6>(6).

=back

=head2 GENERAL OPTIONS

The following are more general options:

=over 4

=item B<-welcome> I<TEXT>

=item B<-prompt> I<PROMPT>

Specifies the pango markup text that is to be displayed in the title
area of the host menu.  As with the B<-banner> option, this option can
easily be supplied by a shell script between L<xdm(1)> and
B<xde-xchooser> that adds the options:

 #!/bin/sh
 /usr/bin/xde-xchooser -welcome "Welcome to X!" $@

When unspecified, the default welcome text is C<Welcome to %s!>, where C<%s>
is the fully qualified domain name of the local host.

=item B<-banner> I<PNGFILE>

Specifies the banner graphic to display in the left pane of the host
menu.  L<xdm(1)> does not provide this option, but it can easily be
invoked by a shell script invoked by L<xdm(1)> that adds the options.
For example:

 #!/bin/sh
 /usr/bin/xde-xchooser -banner /usr/lib/X11/xdm/xde/banner.png $@

When unspecified, the program searches for an image file named
F<${XDG_VENDOR_ID--}banner.png>.

=item B<-splash> I<JPGFILE>

Specifies the graphic to use as the root window background for the
chooser.  L<xdm(1)> does not provide this option, but it can easily be
invoked by a shell script by L<xdm(1)> that adds the options.  For
example:

 #!/bin/sh
 /usr/bin/xde-xchooser -splash /usr/lib/X11/xdm/xde/splash.jpg $@

When unspecified, the program searches for an image file named
F<${XDG_VENDOR_ID:--}splash.jpg>.

=item B<-side> {B<top>|B<left>|B<bottom>|B<right>}

Specifies the side on which the logo (banner) will be displayed.  This
option is currently ignored and the logo will always be placed on the
left side.

=item B<-charset> I<CHARSET>

Specifies the character set to use.  When unspecified, the character
set is determined using the current locale: see L<locale(7)>.

=item B<-language> I<LANGUAGE>

Specifies the language to use.  When unspecified, the language is
determined using the current locale: see L<locale(7)>.

=item B<-icons> I<ICON-THEME>

Specifies the GTK+ icon theme to use.  When unspecified, the icon theme
is automatically determined using desktop and toolkit files.

=item B<-theme> I<GTK2-THEME>

Specifies the GTK+ theme name to use.  When unspecified, the GTK2 theme
is automatically determined using desktop and toolkit files.

=item B<-xde-theme>

Specifies that the GTK+ icon theme and theme name to be used are those
of the X Desktop Environment (XDE) rather than the system default theme.
The default is to specify this flag.

=item B<-vendor> I<VENDOR>

Specifies the vendor identifier for branding.  The default, when
unspecified, is to used the value of environment variables
B<XDG_VENDOR_ID> and B<XDG_MENU_PREFIX> to determine the vendor name and
prefix.

=item B<-xsessions>

Specifies that available X sessions (window managers) should be provided
as a menu on the login window.  This allows a user to select an
available session before logging in.

=item B<-default> I<DEFAULT>

Specifies the default X session (window manager) name that should be
used when no X session is selected by the user.  This default is fed as
an argument to F<~/.xinitrc>.

=item B<-username> I<USERNAME>

Specifies the default user name for login.

=item B<-nosetbg>

Specifies that the background image should not be set by the program.
The default behaviour is to set the background in accordance with the
B<-banner> option.

=item B<-transparent>

Specifies that the login panel should be transparent and that the
widgets should be embedded in the background image.  The default is to
paint the login panel.

=item B<-dry-run>

Specifies that the program should not perform any actions but should
simply print intentions to standard output.  This option is for testing.

=item B<-debug> [I<LEVEL>]

Prints debugging information to standard error during operation.  This
option can be repeated to increase the debugging level.  The default
level is 0.

=item B<-verbose> [I<LEVEL>]

Print diagnostic information to standard error during operation.  This
option can be repeated to increase the verbosity of output.  The default
level is 1.

=back

=head1 X RESOURCES

Most values that affect the look and feel of B<xde-xlogin> may also be
specified as X resources in the B<RESOURCE_MANAGER> database associated
with the X server.  All of these resources can have the specific
resource name and class C<xde-chooser>, C<XDE-Chooser>.  When no resource
is found with the specific name and class, L<xdm(1)> resources with name
and class C<chooser>, C<Chooser> will also be examined for
specified resources.

Note that L<xdm(1)> usually adds the resources contained in the
F</etc/X11/xdm/Xresources> file that is loaded by L<xdm(1)> on startup
to the resource database on the X server.  Chooser resource defaults
(see also L<xdm(1)> and L<xde-xlogin(1)>) are contain in the
F</usr/share/X11/app-defaults/Chooser> file.  Likewise, B<xde-xchooser>
specific resource defaults are contained in the
F</usr/share/X11/app-defaults/XDE-Chooser> file, in accordance with the
convention of naming applications default files after their resource
class.  See also L</FILES>.

B<xde-xchooser> observes the following X11 Resource Manager resources when
loaded by L<xdm(1)> prior to execution:

=over 4

=item B<XDE-XChooser>*B<x>: I<DOUBLE>

Specifies the X position on the monitor as a floating point number
between C<0.0> and C<1.0>, where C<0.0> represents the left edge of the
monitor and C<1.0>, the right edge.  The dialog will be positioned on this
point depending on its gravity (currently static or centered).

=item B<XDE-XChooser>*B<y>: I<DOUBLE>

Specifies the Y position on the monitor as a floating point number
between C<0.0> and C<1.0>, where C<0.0> represents the top edge of the
monitor and C<1.0>, the bottom edge.  The dialog will be positioned on
this point depending on its gravity (currently static or centered).

=item B<XDE-XChooser>*B<debug>: I<INTEGER>

Provides the debugging level in the same fasion as the B<-debug> command
line option.

=item B<XDE-XChooser>*B<banner>: I<PATH>

Provides the banner to use for the branding logo in the same fashion as
the B<-banner> command line option.

=item B<XDE-XChooser>*B<splash>: I<PATH>

Provides the background to use for the root window in the same fashion
as the B<-splash> command line option.

=item B<XDE-XChooser>*B<welcome>: I<MARKUP>

Provides the welcome message to use for the root window in the same
fashion as the B<-welcome> command line option.

=item B<XDE-XChooser>*B<charset>: I<CHARSET>

Provides the character set in the same fashion as the B<-charset>
command line option.

=item B<XDE-XChooser>*B<language>: I<LANG>

Provides the language in the same fashion as the B<-language> command
line option.

=item B<XDE-XChooser>*B<theme.icon>: I<NAME>

Provides the XDG icon theme name.

=item B<XDE-XChooser>*B<theme.name>: I<NAME>

Provides the XDG theme name (for GTK+).

=item B<XDE-XChooser>*B<theme.cursor>: I<NAME>

Provides the XDG cursor theme name.

=item B<XDE-XChooser>*B<theme.xde>: {B<true>|B<false>}

When I<true>, specifies that the system XDE desktop theme should be used
instead of the system GTK+ theme.

=item B<XDE-XChooser>*B<side>: {B<left>|B<right>|B<top>|B<bottom>}

Speecifies the side on which the logo (banner) should appear.  Currently
only I<left> is supported.

=item B<XDE-XChooser>*B<user.default>: I<USERNAME>

Specifies a default use name to use for the login (when a login is
provided).  Note that a default user name will not be presented when it
can be detected that the display is remote from the current host.

=item B<XDE-XChooser>*B<autologin>: {B<true>|B<false>}

When I<true>, specifies that the user defined in
B<XDE-XChooser>*B<user.default> should be automatically logged into a
session without requiring a password.  It may be necessary for such a
user to be a member of the C<autologin> group.  Auto login will be
suppressed when it can be detected that the display is remote from the
current host.

=item B<XDE-XChooser>*B<vendor>: I<VENDOR-ID>

Provides a vendor identifier for use in lookup up banners and
backgrounds automatically, as with the B<-vendor> command line option.

=item B<XDE-XChooser>*B<prefix>: I<MENU-PREFIX>

Provides a vendor identifier as a menu prefix (C<XDG_MENU_PREFIX>)
instead of as a plain identifier.  The prefix normally has a dash (C<->)
appended.

=item B<XDE-XChooser>*B<login.permit>: {B<true>|B<false>}

The XDMCP Chooser has control of an X Display in the same manner as the
XDMCP Greeter program and may provide an immediate login option in
addition to a list of XDMCP hosts.  When I<true>, this option specifies
that this login is to be presented as an option to users of the XDMCP
Chooser.

=item B<XDE-XChooser>*B<login.remote>: {B<true>|B<false>}

The XDMCP Chooser may provide a direct login option to the user of the
chooser.  When I<true>, this option specifies that remote displays will
be given the same opportunity to log in directly.  When I<false>,
displays that are detected as remote from the host will no be offered a
direct login.

=item B<XDE-XChooser>*B<xsession.chooser>: {B<true>|B<false>}

=item B<XDE-XChooser>*B<xsession.execute>: {B<true>|B<false>}

=item B<XDE-XChooser>*B<xsession.default>: I<APPID>

=item B<XDE-XChooser>*B<xsession.setbg>: {B<true>|B<false>}

=item B<XDE-XChooser>*B<xsession.transparent>: {B<true>|B<false>}

=back

B<xde-xchooser> may observe some of the resources intended for the L<xdm(1)>
chooser, such as:

=over 4

=item B<Chooser>*B<geometry>

=item B<Chooser>*B<allowShellResize>

=item B<Chooser>*B<viewport.forceBars>

=item B<Chooser>*B<label.font>

=item B<Chooser>*B<label.label>

=item B<Chooser>*B<list.font>

=item B<Chooser>*B<Command.font>

=back

B<xde-xchooser> may observe some of the resources intended for the L<xdm(1)>
login, such as:

=over 4

=item B<xlogin>.B<Login.width>: I<INTEGER>

=item B<xlogin>.B<Login.height>: I<INTEGER>

=item B<xlogin>.B<Login.x>: I<INTEGER>

=item B<xlogin>.B<Login.y>: I<INTEGER>

=item B<xlogin>.B<foreground>: I<XCOLOR>

=item B<xlogin>.B<background>: I<XCOLOR>

=item B<xlogin>.B<face>: I<XFTFONT>

=item B<xlogin>.B<font>: I<XFONT>

=item B<xlogin>.B<greeting>: I<STRING>

=item B<xlogin>.B<unsecureGreeting>: I<STRING>

=item B<xlogin>.B<greetFace>: I<XFTFONT>

=item B<xlogin>.B<greetFont>: I<XFONT>

=item B<xlogin>.B<greetColor>: I<XCOLOR>

=item B<xlogin>.B<namePrompt>: I<STRING>

=item B<xlogin>.B<passwdPrompt>: I<STRING>

=item B<xlogin>.B<promptFace>: I<XFTFONT>

=item B<xlogin>.B<promptFont>: I<XFONT>

=item B<xlogin>.B<promptColor>: I<XCOLOR>

=item B<xlogin>.B<changePasswdMessage>: I<STRING>

=item B<xlogin>.B<fail>: I<STRING>

=item B<xlogin>.B<failFace>: I<XFTFONT>

=item B<xlogin>.B<failFont>: I<XFONT>

=item B<xlogin>.B<failColor>: I<XCOLOR>

=item B<xlogin>.B<failTimeout>: I<INTEGER>

=item B<xlogin>.B<logoFileName>: I<PATH>

=item B<xlogin>.B<logoPadding>: I<INTEGER>

=item B<xlogin>.B<useShape>: {B<true>|B<false>}

=item B<xlogin>.B<hiColor>: I<XCOLOR>

=item B<xlogin>.B<shdColor>: I<XCOLOR>

=item B<xlogin>.B<frameWidth>: I<INTEGER>

=item B<xlogin>.B<innerFrameWidth>: I<INTEGER>

=item B<xlogin>.B<sepWidth>: I<INTEGER>

=item B<xlogin>.B<allowRootLogin>: {B<true>|B<false>}

=item B<xlogin>.B<allowNullPasswd>: {B<true>|B<false>}

=item B<xlogin>.B<echoPasswd>: {B<true>|B<false>}

=item B<xlogin>.B<echoPasswdChar>: I<STRING>

=item B<xlogin>.B<borderWidth>: I<INTEGER>

=back

L<xdm(1)> specifies which chooser to execute in its configuration file
F</usr/lib/X11/xdm/xdm-config>:

=over 4

=item B<DisplayManager>.I<DISPLAY>.B<chooser>

This option, described in L<xdm(1)>, is use to tell L<xdm(1)> which
program to run as a chooser.  This should be set to
F</usr/lib/X11/xdm/xde-xchooser>.  See the B<CHOOSER> section of the
L<xdm(1)> manual page.

=back

=head1 FILES

=over 4

=item F</usr/lib/X11/xdm/xde-xchooser>

The default location of the B<xde-xchooser> executable.

=item F</usr/lib/X11/xdm/banner.png>

The default location of the banner graphic.

=item F</etc/X11/xdm/Xresources>

The normal location of the X resources file for L<xdm(1)>.

=item F</etc/X11/xdm/xde/Xresources>

Because this chooser is allociated with XDE, a complete set of
L<xdm(1)> configuration files, including the X resources file containing
B<XDE-Chooser> resources are contained in the F</etc/X11/xdm/xde>
subdirectory.  Application defaults are not loaded from anywhere else
for security.

=item F</usr/share/X11/app-defaults/XDE-Chooser>

X resource defaults for B<xde-xchooser>.

=back

=head1 USAGE

=head1 BUGS

B<xde-xchooser> had no known bugs at the time of release.  Please report
bugs for current versions to the source code repository at
L<https://github.com/bbidulock/xde-session/issues>.

=head1 HISTORY

This program was originally written as a GTK2-perl script, but I don't
like running GTK2-perl scripts as root, do you?  Also, I wanted to
permit the program to redirect a user X session, or to redirect a Xephyr
session, and this close interaction with the X server was not available
in perl.  You can check out the original perl version at
L<http://github.com/bbidulock/gchooser>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@cpan.org>

See B<--copying> for full copyright notice and copying permissions.

=head1 SEE ALSO

L<xdm(1)>, L<Xnest(1)>, L<Xephyr(1)>, X Display Manager Control Protocol
Specification.

=head1 LICENSE

See the F<COPYING> file in the distribution or use the B<--copying> flag
to display copying permissions.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
