=pod

=head1 NAME

xde-xlogin - log into an X session

=head1 SYNOPSIS

B</usr/lib/X11/xdm/xde-xlogin> [I<OPTIONS>]

=head1 DESCRIPTION

B<xde-xlogin> is an L<xdm(1)> xlogin and chooser replacement that
provides a much nicer appearing login screen for L<xdm(1)>.
It is designed to let L<xdm(1)> do the heavy lifting of coordinating the
majority of the XDMCP protocol while providing a more aesthetic
appearance.

=head1 OPTIONS

No options are necessary.  When launched by L<xdm(1)>, it will provide
the appropriate arguments.  B<xde-xlogin> can be launched directly on
the command line of an x-terminal to test its appearance and operation.
In this mode, arguments are still required but no options.  Absence of
the B<-xdmAddress>, B<-clientAddress> and B<-connectionType> options
indicates to B<xde-xlogin> that it was not launched by L<xdm(1)> or an
L<xdm(1)> work-alike as a chooser.  See L</USAGE> for more information.

=head2 COMMAND OPTIONS

When no command option is specified, B<xde-xlogin> executes the program.
The following command options, when specified, print information instead
of running the program.

=over 4

=item B<-H>, B<-help>

Instead of operating normally, the program prints usage information to
standard output and exits.

=item B<-V>, B<--version>

Instead of operating normally, the program prints detailed version
information and exits.

=item B<-C>, B<--copying>

Instead of operating normally, the program prints detailed copying
permissions and exits.

=back


=head2 GENERAL OPTIONS

B<xde-xlogin> provides a set of general options that are not supported
by the L<xdm(1)> greeter or chooser.  To supply these options requires
an intermediate script that specifies them and echoes the L<xdm(1)>
chooser options.  So that an intermediate script is not necessary,
L<xdm(1)> provides an F<Xresources> files containing X resources that
are used instead of command line options to tailor the look and feel of
the greeter and chooser.  As a result, the use of the following command
line options are not necessary and are really only used for testing.

The following are the more general options:

=over 4

=item B<-prompt> I<MARKUP>

Specifies the F<pango> markup text that is to be displayed in the title
area of the host menu.  As with the B<-banner> option, this option can
easily be supplied by a shell script between L<xdm(1)> and
B<xde-xlogin> that adds the options:

 #!/bin/sh
 /usr/lib/X11/xdm/xde-xlogin -prompt "Welcome to X!" \
	 -banner /usr/lib/X11/xdm/banner.png $@

When unspecified, the default welcome text is C<Welcome to %s!>, where C<%s>
is the fully qualified domain name of the local host.

=item B<-banner> I<PNGFILE>

Specifies the banner graphic to display in the left pane of the host
menu.  L<xdm(1)> does not provide this option, but it can easily be
invoked by a shell script invoked by L<xdm(1)> that adds the options.
For example:

 #!/bin/sh
 /usr/lib/X11/xdm/xde-xlogin -banner /usr/lib/X11/xdm/xde/banner.png $@

When unspecified, the program searches for an image file named
F<${XDG_VENDOR_ID--}banner.{xpm,png,jpg,svg}> in the subdirectory
F<images> in XDG data directories.

=item B<-splash> I<JPGFILE>

Specifies the graphic to use as the root window background for the
greeter and chooser.  L<xdm(1)> does not provide this option, but it can easily be
invoked by a shell script by L<xdm(1)> that adds the options.  For
example:

 #!/bin/sh
 /usr/lib/X11/xdm/xde-xlogin -splash /usr/lib/X11/xdm/xde/splash.jpg $@

When unspecified, the program searches for an image file named
F<${XDG_VENDOR_ID:--}splash.{xpm,png,jpg,svg}> in the subdirectory
F<images> in XDG data directories.

=item B<-side> {B<top>|B<left>|B<bottom>|B<right>}

Specifies the side on which to display branding (the banner graphic).
Can be one of I<top>, I<left>, I<bottom> or I<right>.  When unspecified,
the default is I<left>.

=item B<-charset> I<CHARSET>

Specifies the character set to use.  When unspecified, the character
set is determined using the current locale: see L<locale(7)>.

=item B<-language> I<LANGUAGE>

Specifies the language to use.  When unspecified, the language is
determined using the current locale: see L<locale(7)>.

=item B<-icons> I<ICON-THEME>

Specifies the GTK+ icon theme to use.  When unspecified, the icon theme
is automatically determined using desktop and toolkit files.

=item B<-theme> I<GTK2-THEME>

Specifies the GTK+ theme name to use.  When unspecified, the GTK2 theme
is automatically determined using desktop and toolkit files.

=item B<-xde-theme>

Specifies that the GTK+ icon theme and theme name to be used are those
of the X Desktop Environment (XDE) rather than the system default theme.
The default is to specify this flag.

=item B<-vendor> I<VENDOR>

Specifies the vendor identifier for branding.  The default, when
unspecified, is to used the value of environment variables
B<XDG_VENDOR_ID> and B<XDG_MENU_PREFIX> to determine the vendor name and
prefix.

=item B<-xsessions>

Specifies that available X sessions (window managers) should be provided
as a menu on the login window.  This allows a user to select an
available session before logging in.

=item B<-default> I<DEFAULT>

Specifies the default X session (window manager) name that should be
used when no X session is selected by the user.  This default is fed as
an argument to F<~/.xinitrc>.

=item B<-username> I<USERNAME>

Specifies the default user name for login.

=item B<-nosetbg>

Specifies that the background image should not be set by the program.
The default behaviour is to set the background in accordance with the
B<-banner> option.

=item B<-transparent>

Specifies that the login panel should be transparent and that the
widgets should be embedded in the background image.  The default is to
paint the login panel.

=item B<-n>, B<--dry-run>

Specifies that the program should not perform any actions but should
simply print intentions to standard output.  This option is for testing.

=item B<-D>, B<--debug> [I<LEVEL>]

Increase, or set to I<LEVEL>, the debugging verbosity.  The default
debugging verbosity level is zero (0), which means to output no
debugging information.  When non-zero, debugging information will be
printed to standard error.

=item B<-v>, B<--verbose> [I<LEVEL>]

Increase, or set to I<LEVEL>, the output verbosity.  The default output
verbosity level is one (1), which means to output normal information to
standard output.  When set to zero (0), no output will be printed to
standard output. 

=back

=head1 EXIT STATUS

When run as a I<greeter> program, instead of communicating using a
socket, the I<greeter> program can provide further instructions to
L<xdm(1)> based on the exit status of the I<greeter> program.
Therefore, the program provides the exit status values as follows:

=over 4

=item 0 - B<OBEYSESS_DISPLAY>

Obey the multiple sessions resource.

=item 1 - B<REMANAGE_DISPLAY>

Force re-management of the display.

=item 2 - B<UNMANAGE_DISPLAY>

Force deletion of the display.

=item 3 - B<RESERVER_DISPLAY>

Force server termination.

=item 4 - B<OPENFAILED_DISPLAY>

L<XOpenDisplay(1x)> failed, retry.

=back

=head1 X RESOURCES

Most values that affect the look and feel of B<xde-xlogin> may also be
specified as X resources in the B<RESOURCE_MANAGER> database associated
with the X server.  All of these resources can have the specific
resource name and class (C<xde-xlogin>, C<XDE-XLogin>).  When no resource
is found with the specific name and class, L<xdm(1)> resources with name
and class (C<xlogin.Login>, C<Xlogin.Login>) will also be examined for
specified resources.

Note that L<xdm(1)> usually adds the resources contained in the
F</etc/X11/xdm/Xresources> file that is loaded by L<xdm(1)> on startup
to the resource database on the X server.  Chooser resource defaults
(see also L<xdm(1)> and L<xde-xchooser(1)>) are contained in the
F</usr/share/X11/app-defaults/Chooser> file.  Likewise, B<xde-xlogin>
specific resource defaults are contained in the
F</usr/share/X11/app-defaults/XDE-XLogin> file, in accordance with the
convention of naming applications default files after their resource
class. See also L</FILES>.

B<xde-xlogin> observes the following X11 Resource Manager resources when
loaded by L<xdm(1)> prior to execution:

=over 4

=item B<xde-xlogin>.B<x>: I<DOUBLE>

Specifies the X position on the monitor as a floating point number
between C<0.0> and C<1.0>, where C<0.0> represents the left edge of the
monitor and C<1.0>, the right edge.  The dialog will be positioned on this
point depending on its gravity (currently static or centered).

=item B<xde-xlogin>.B<y>: I<DOUBLE>

Specifies the Y position on the monitor as a floating point number
between C<0.0> and C<1.0>, where C<0.0> represents the top edge of the
monitor and C<1.0>, the bottom edge.  The dialog will be positioned on
this point depending on its gravity (currently static or centered).

=item B<xde-xlogin>.B<debug>: I<INTEGER>

Provides the debugging level in the same fashion as the B<-debug>
command line option.

=item B<xde-xlogin>.B<banner>: I<PATH>

Provides the banner to use for the branding logo in the same fashion as
the B<-banner> command line option.  Specifies the I<PATH> to the banner
graphic to display in the left pane of the host menu.  When unspecified,
the program searches for an image file name
F<${XDG_VENDOR_ID--}banner.{xpm,png,jpg,svg}> in the subdirectory
F<images> in XDG data directories.

=item B<xde-xlogin>.B<splash>: I<PATH>

Provides the background to use for the root window in the same fashion
as the B<-splash> command line option.

=item B<xde-xlogin>.B<welcome>: I<MARKUP>

Provides the welcome message to use for the root window in the same
fashion as the B<-welcome> command line option.  Specifies the F<pango>
markup text, I<MARKUP>, that is to be display in the title area of the
host menu.

=item B<xde-xlogin>.B<charset>: I<CHARSET>

Provides the character set in the same fashion as the B<-charset>
command line option.

=item B<xde-xlogin>.B<language>: I<LANG>

Provides the language in the same fashion as the B<-language> command
line option.

=item B<xde-xlogin>.B<theme.icon>: I<NAME>

Provides the XDG icon theme name.
Specifies the value of the B<-icons> option.

=item B<xde-xlogin>.B<theme.name>: I<NAME>

Provides the XDG theme name (for GTK+).
Specifies the value of the B<-theme> option.

=item B<xde-xlogin>.B<theme.cursor>: I<NAME>

Provides the XDG cursor theme name.

=item B<xde-xlogin>.B<theme.xde>: {B<true>|B<false>}

When I<true>, specifies that the system XDE desktop theme should be used
instead of the system GTK+ theme.
Specifies the value of the B<-xde-theme> option.

=item B<xde-xlogin>.B<side>: {B<left>|B<right>|B<top>|B<bottom>}

Specifies the side on which the logo (banner) should appear.  Currently
only I<left> is supported.
Specifies the value of the B<-side> option.

=item B<xde-xlogin>.B<user.default>: I<USERNAME>

Specifies a default use name to use for the login (when a login is
provided).  Note that a default user name will not be presented when it
can be detected that the display is remote from the current host.
Specifies the value of the B<-username> option.

=item B<xde-xlogin>.B<autologin>: {B<true>|B<false>}

When I<true>, specifies that the user defined in
B<xde-xlogin>.B<user.default> should be automatically logged into a
session without requiring a password.  It may be necessary for such a
user to be a member of the C<autologin> group.  Auto login will be
suppressed when it can be detected that the display is remote from the
current host.

=item B<xde-xlogin>.B<vendor>: I<VENDOR-ID>

Provides a vendor identifier for use in lookup up banners and
backgrounds automatically, as with the B<-vendor> command line option.

=item B<xde-xlogin>.B<prefix>: I<MENU-PREFIX>

Provides a vendor identifier as a menu prefix (C<XDG_MENU_PREFIX>)
instead of as a plain identifier.  The prefix normally has a dash (C<->)
appended.

=item B<xde-xlogin>.B<login>*B<permit>: {B<true>|B<false>}

The XDMCP Chooser has control of an X Display in the same manner as the
XDMCP Greeter program and may provide an immediate login option in
addition to a list of XDMCP hosts.  When I<true>, this option specifies
that this login is to be presented as an option to users of the XDMCP
Chooser.

=item B<xde-xlogin>.B<login>*B<remote>: {B<true>|B<false>}

The XDMCP Chooser may provide a direct login option to the user of the
chooser.  When I<true>, this option specifies that remote displays will
be given the same opportunity to log in directly.  When I<false>,
displays that are detected as remote from the host will no be offered a
direct login.

=item B<xde-xlogin>.B<xsession.chooser>: {B<true>|B<false>}

Specifies the value of the B<-xsession> option.

=item B<xde-xlogin>.B<xsession.execute>: {B<true>|B<false>}

=item B<xde-xlogin>.B<xsession.default>: I<APPID>

Specifies the value of the B<-default> option.

=item B<xde-xlogin>.B<setbg>: {B<true>|B<false>}

Specifies the value of the B<-nosetbg> option.

=item B<xde-xlogin>.B<transparent>: {B<true>|B<false>}

Specifies the value of the B<-transparent> option.

=item B<xde-xlogin>.B<face>: I<XFTFONT>

The typeface used to display the input typed by the user.
The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.face>
resource is used instead.

=item B<xde-xlogin>.B<greetFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.greetFace>
resource is used instead.

=item B<xde-xlogin>.B<greetColor>

The default is C<grey20>.
If this resource is not specified, the
B<xlogin>.B<Login.greetColor>
resource is used instead.

=item B<xde-xlogin>.B<promptFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.promptFace>
resource is used instead.

=item B<xde-xlogin>.B<promptColor>

The default is C<grey20>.
If this resource is not specified, the
B<xlogin>.B<Login.promptColor>
resource is used instead.

=item B<xde-xlogin>.B<inputFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.inputFace>
resource is used instead.

=item B<xde-xlogin>.B<inputColor>

The default is C<grey20>.
If this resource is not specified, the
B<xlogin>.B<Login.inputColor>
resource is used instead.

=item B<xde-xlogin>.B<failFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.failFace>
resource is used instead.

=item B<xde-xlogin>.B<failColor>

The default is C<red>.
If this resource is not specified, the
B<xlogin>.B<Login.failColor>
resource is used instead.

=back

When specific B<xde-xlogin> resources are not specified,
B<xde-xlogin> falls back the using the resources specified for its
default greeter by L<xdm(1)>, as follows:

=over 4

=item B<xlogin>.B<Login.width>: I<INTEGER>

Specifies the width of the login widget, either in pixels, or when
suffixed with a C<%>, as a decimal percentage of the display width.
The default is dynamic width, depending on the contents of widgets.

=item B<xlogin>.B<Login.height>: I<INTEGER>

Specifies the height of the login widget, either in pixels, or when
suffixed with a C<%>, as a decimal percentage of the display height.
The default is dynamic height, depending on the contents of widgets.

=item B<xlogin>.B<Login.x>: I<INTEGER>

Specifies the x-axis position of the login widget.
The default is centred on the screen.

=item B<xlogin>.B<Login.y>: I<INTEGER>

Specifies the y-axis position of the login widget.
The default is centred on the screen.

=item B<xlogin>.B<Login.foreground>: I<XCOLOR>

The foreground colour used to display the input typed by the user.
The default is C<grey20>.

=item B<xlogin>.B<Login.background>: I<XCOLOR>

The background colour used to display the input typed by the user.
The default is C<LightSteelBlue3>.

=item B<xlogin>.B<Login.face>: I<XFTFONT>

The typeface used to display the input typed by the user when built with
Xft support.
The default is C<Sans:size=12:bold>.

=item B<xlogin>.B<Login.font>: I<XFONT>

The font used to display the input typed by the user when not built with
Xft support.
This resource not used by B<xde-xlogin>.

=item B<xlogin>.B<Login.greeting>: I<STRING>

A string that identifies this window.  The L<xdm(1)> default is C<X
Window System>.
The default is the value specified by command line option B<-welcome>,
or C<Welcome to CLIENTHOST>.

=item B<xlogin>.B<Login.unsecureGreeting>: I<STRING>

When X authorization is requested in the configuration file for this
display and none is in use, this greeting replaces the standard
greeting.
The default is C<This is an unsecure session>.

=item B<xlogin>.B<Login.greetFace>: I<XFTFONT>

The face used to display the greeting when built with Xft support.  The
L<xdm(1)> default is C<Serif-24:italic>.
The default is C<Sans:size=12:bold>.

=item B<xlogin>.B<Login.greetFont>: I<XFONT>

The font used to display the greeting when not built with Xft support.
This resource not used by B<xde-xlogin>.

=item B<xlogin>.B<Login.greetColor>: I<XCOLOR>

The color used to display the greeting.
The default is C<grey20>.

=item B<xlogin>.B<Login.namePrompt>: I<STRING>

The string display to prompt for a user name.  L<xrdb(1)> strips
trailing white space from resource values, so to add spaces at the end
of the prompt (usually a nice thing), add spaces escaped with
backslashes.  The L<xdm(1)> default is C<Login:  >.
The default is C<Username:  >.

=item B<xlogin>.B<Login.passwdPrompt>: I<STRING>

The string displayed to prompt for a password, when not using an
authentication system such as PAM that provides its own prompts.  The
L<xdm(1)> default is C<Password:  >.
The default is C<Password:  >.

=item B<xlogin>.B<Login.promptFace>: I<XFTFONT>

The face used to display prompts when build with Xft support.  The
L<xdm(1)> default is C<Serif-18:bold>.
The default is C<Sans:size=12:bold>.

=item B<xlogin>.B<Login.promptFont>: I<XFONT>

The font used to display prompts when not built with Xft support.
This resource not used by B<xde-xlogin>.

=item B<xlogin>.B<Login.promptColor>: I<XCOLOR>

The color used to display prompts.
The default is C<grey20>.

=item B<xlogin>.B<Login.inputFace>: I<XFTFONT>

The face used to display user input when built with Xft support.
The default is C<Sans:size=12:bold>.

=item B<xlogin>.B<Login.inputFont>: I<XFONT>

The font used to display user input when not built with Xft support.
This resource not used by B<xde-xlogin>.

=item B<xlogin>.B<Login.inputColor>: I<XCOLOR>

The color used to display user input.
The default is C<grey20>.

=item B<xlogin>.B<Login.changePasswdMessage>: I<STRING>

A message that is displayed when the user's password has expired.  The
L<xdm(1)> default is C<Password Change Required>.
The default is supplied by the PAM subsystem.

=item B<xlogin>.B<Login.fail>: I<STRING>

A message that is displayed when the authentication fails, when not
using an authentication system such as PAM that provides its own
prompts.  The L<xdm(1)> default is C<Login incorrect>.
The default is supplied by the PAM subsystem.

=item B<xlogin>.B<Login.failFace>: I<XFTFONT>

The face used to display the failure message when built with Xft
suppport.  The L<xdm(1)> default is C<Serif-18:bold>.
The default is C<Sans:size=12:bold>.

=item B<xlogin>.B<Login.failFont>: I<XFONT>

The font used to display the failure message when not built with Xft
support.
This resource not used by B<xde-xlogin>.

=item B<xlogin>.B<Login.failColor>: I<XCOLOR>

The default color used to display the failure message.
The default is C<red>.

=item B<xlogin>.B<Login.failTimeout>: I<INTEGER>

The number of seconds that the failure message is displayed, before
another login attempt is permitted.
The L<xdm(1)> default is C<10>.
The PAM subsystem provides this delay.

=item B<xlogin>.B<Login.logoFileName>: I<PATH>

Name of an XPM format pixmap to display in the greeter window, if built
with XPM support.  The L<xdm(1)> default is no pixmap.
The default is F</etc/X11/xdm/xde/banner.png>.

=item B<xlogin>.B<Login.logoPadding>: I<INTEGER>

The number of pixels of space between the logo pixmap and other elements
of the greeter window, if the pixmap is displayed.  The L<xdm(1)>
default is C<5>.
The default is C<8>.

=item B<xlogin>.B<Login.useShape>: {B<true>|B<false>}

If set to C<true>, when built with XPM support, attempt to use the X
Non-Rectangular window Shape Extension to set the window shape.  The
L<xdm(1)> default is C<true>.
The default is C<true>.

=item B<xlogin>.B<Login.hiColor>: I<XCOLOR>

Raised appearance bezels may be drawn around the greeter frame and text
input boxes by setting this resource.
B<hiColor> is the highlight color, used on the top and left sides of the
frame, and the bottom and right sides of the text input areas.
The L<xdm(1)> default is the foreground color, providing a flat
appearance.
The default is C<grey80>.
This GTK+ version defaults to the active GTK theme.

=item B<xlogin>.B<Login.shdColor>: I<XCOLOR>

Raised appearance bezels may be drawn around the greeter frame and text
input boxes by setting this resource.
B<shdColor> is the shadow color, used on the bottom and right sides of
the frame, and the top and left sides of the text input areas.
The L<xdm(1)> default is the foreground color, providing a flat
appearance.
The default is C<grey20>.
This GTK+ version defaults to the active GTK theme.

=item B<xlogin>.B<Login.frameWidth>: I<INTEGER>

The width in pixels of the area around the greeter frame drawn in
B<hiColor> and B<shdColor>.
For GTK, when set to C<0>, the frame will be drawn flat; otherwise, it
will be drawn raised.
The default is C<2>.

=item B<xlogin>.B<Login.innerFrameWidth>: I<INTEGER>

The width in pixels of the area around text input areas drawn in
B<hiColor> and B<shdColor>.
The default is C<2>.
For GTK, when set to C<0>, the text areas will be drawn flat; otherwise,
they will be drawn sunken.

=item B<xlogin>.B<Login.sepWidth>: I<INTEGER>

The width in pixels of the bezel line between the greeting and input
areas drawn in B<hiColor> and B<shdColor>.
For GTK, when set to C<0>, the line will be drawn flat; otherwise it
will be drawn etched.
The default is C<2>.

=item B<xlogin>.B<Login.allowRootLogin>: {B<true>|B<false>}

When set to C<false>, do not allow root (and any other user with uid of
zero) to log in directly.
This setting is only checked by some authentication back-ends at this
time.
The default is C<true>.
This option is better set using the C<xdm-login> PAM service settings.

=item B<xlogin>.B<Login.allowNullPasswd>: {B<true>|B<false>}

If set to C<true>, allow an otherwise failing password match to succeed
if the account does not require a password at all.  The default is
C<false>, so only users that have passwords assigned can log in.
This option is better set using the C<xdm-login> PAM service settings.

=item B<xlogin>.B<Login.echoPasswd>: {B<true>|B<false>}

When set C<true>, a placeholder character (B<echoPasswdChar>) will be
shown for fields normally set to not echo, such as password input.  The
L<xdm(1)> default is C<false>.
The default is C<true>.

=item B<xlogin>.B<Login.echoPasswdChar>: I<STRING>

Character to display if B<echoPasswd> is C<true>.  The default is C<*>.
When set to an empty value, the cursor will advance for each character
input, but no text will be drawn.

=item B<xlogin>.B<Login.borderWidth>: I<INTEGER>

The width in pixels between the edge of the greeter frame and its
content.
The default is C<3>.

=item B<xlogin>.B<Login.translations>: I<STRING>

This resource not used by B<xde-xlogin>.

=back

=head1 CONFIGURATION

L<xdm(1)> specifies which chooser and greeter to execute in its
configuration file F</usr/lib/X11/xdm/xdm-config>:

=over 4

=item B<DisplayManager>.I<DISPLAY>.B<chooser>

This option, described in L<xdm(1)>, is used to tell L<xdm(1)> which
program to run as a chooser.  This should be set to
F</usr/lib/X11/xdm/xde-xlogin>.  See L<xdm(1)/CHOOSER>.

=item B<DisplayManager>.I<DISPLAY>.B<greeter>

This option, described in L<xdm(1)>, is used to tell L<xdm(1)> which
program to run as a greeter.  This should be set to
F</usr/lib/X11/xdm/xde-xlogin>.  See L<xdm(1)/AUTHENTICATION WIDGET>.

=back

=head1 FILES

=over 4

=item F</usr/lib/X11/xdm/xde-xlogin>

The default location of the B<xde-xlogin> executable.
As this is not useful for normal users, it does not reside in the
F</usr/bin> directory.

=item F</usr/lib/X11/xdm/banner.png>

The default location of the banner graphic.

=item F</etc/X11/xdm/Xresources>

The normal location of the X resources file for L<xdm(1)>.  Normally,
L<xdm(1)> will merge the resources found in this file into the X display
B<RESOURCE_MANAGER> property on the root window before launching the
greeter or chooser programs.

=item F</etc/X11/xdm/xde/Xresources>

Because the greeter and chooser is associated with XDE, a complete set of
L<xdm(1)> configuration files, including the X resources file containing
B<XDE-XLogin> resources are contained in the F</etc/X11/xdm/xde>
subdirectory.  Application defaults are not loaded from anywhere else
for security.

=item F</usr/share/X11/app-defaults/XDE-XLogin>

X resource defaults for B<xde-xlogin>.
The program will load the default resources from this file and then
merge the resources specified in the B<RESOURCE_MANAGER> property on the
X display.  L<xdm(1)> will normally use L<xrdb(1)> to merge the
resources from the F</etc/X11/xdm/Xresources> into the
B<RESOURCE_MANAGER> property on the X display before launching the login
or greeter program.

=back

=head1 USAGE

=head1 BUGS

B<xde-xlogin> had no known bugs at the time of release.  Please report
bugs for current versions to the source code repository at
L<https://github.com/bbidulock/xde-session/issues>.

=head1 HISTORY

I used to use a patched version of L<slim(1)> for this purpose; however,
L<slim(1)> has deficiencies with regard to establishing XDE sessions and
has no provision for being used as a B<chooser>.

Historically, L<xdm(1)> has provided a I<greeter> and a I<chooser>.  The
I<greeter> was a graphical login program that was integrated with
L<xdm(1)>.  The I<chooser> was a graphical XDCMP chooser program that,
while part of the XDM distribution, was a separate program launched by
L<xdm(1)>.  Both of these programs used the archaic Athena widget set.

The XDE fork of L<xdm(1)> provides for a separate I<greeter> program to
be used for graphical login.  Originally, XDE used a modified version of
the L<slim(1)> login manager to act also as a I<greeter> for L<xdm(1)>.
A I<chooser> program was written using perl-gtk2 to act as a much nicer
looking and more fully IPv6 functional I<chooser> program.

This then begged the question as to why there needed to be a separate
I<greeter> and I<chooser>.  Why should not the user be able to login to
the local machine, or choose to login to a remote machine instead.
After all, choosing the local machine from the I<greeter> functions
similar to a I<greeter>.

L<slim(1)> took the approach that logging into an X server is not that
terribly different to unlocking a screen saver.  Why should not the same
appearance code be used for both.  This led XDE to use a related
program, L<xde-xlock(1)> to provide the screen locking mechanism for XDE
in the same fashion as the display manager programs.

Traditional display managers for Linux, such as L<gdm(1)>, have also
taken the approach that choosing an X session (well, at least an
C<XSession> F<.desktop> file to run) could also be performed during
login, instead of selecting one after the login process.

=head1 SEE ALSO

L<xdm(1)>,
L<xqproxy(1)>,
L<xde-xlogin(1)>,
L<xde-xchooser(1)>,
L<slim(1)>,
L<xde-xlock(1)>,
L<Xnest(1)>,
L<Xephyr(1)>,
L<X Display Manager Control Protocol>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

See B<--copying> for full copyright notice and copying permissions.

=head1 LICENSE

See the F<COPYING> file in the distribution or use the B<--copying> flag
to display copying permissions.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
