=head1 NAME

xde-chooser -- choose and XDG desktop session to execute

=head1 SYNOPSIS

B<xde-chooser> [I<OPTIONS>] [I<SESSION>]

=head1 DESCRIPTION

B<xde-chooser> is a gtk2-perl application that can be launched from
F<~/.xinitrc> to choose the X session that will be launched, or can be
launched from a window manager or session logout script to switch the
sessions.  The menu can also provide the choice for the user to perform
actions on the box such as powering off the computer, restarting the
computer, etc.

When a selection is made or logout/disconnect is selected,
B<xde-chooser> prints the selected session name or the special name
C<logout> to standard output and exits with a zero exit status.  On
error, a diagnostic message is printed to standard error and a non-zero
exit status is returned.

=head1 OPTIONS

B<xde-chooser> uses L<Getopt::Long(3pm)> to parse options, so
abbreviated or single-dash long options are recognized when not
ambiguous.  B<xde-chooser> accepts the following options:

=over

=item B<--help>, B<-h>

Print usage information to standard error containing current defaults
and exit.

=item B<--verbose>, B<-v>

Print debugging information to standard error during operation.

=item B<--prompt>, B<-p>

Prompt the user for the session regardless of the value of the
I<SESSION> argument.

=item B<--banner>, B<-b> I<BANNER>

Specifies a custom login logo.  When unspecified, B<xde-chooser> will
use a branded logo that depends on environment variables.  This option
is compatible with L<xde-logout(1)>.

=item B<--side>, B<-s> {B<left>|B<top>|B<right>|B<bottom>}

Specifies the side of the window on which the logo will be placed.  This
option is recognized for compatability with L<lxsession-logout(1)>.
B<xde-logout> always places the logo on the left and this option is
ignored.

=item B<--noask>, B<-n>

Do not ask the user whether she wishes to set the current session as the
default session when I<SESSION> is specified or chosen as something
different than the current default.

=item B<--charset>, B<-c> I<CHARSET>

Specify the character set with which to output the menu.  Defaults to
the character set in use by the current locale.

=item B<--language>, B<-l> I<LANGUAGE>

Specify the output language for the menu.  Defaults to the language set
in the current locale.

=item B<--default>, B<-d>

When a I<SESSION> is specified, also set the future default to I<SESSION>.

=item B<--icons>, B<-i> I<THEME>

Specifies the icon theme to use.  Otherwise, the user's default gtk2
icon theme will be used (i.e. from F<$HOME/.gtkrc-2.0>).

=item B<--theme>, B<-t> I<THEME>

Specifies the Gtk2 theme to use.  Otherwise, the user's default gtk2
theme will be used (i.e. from F<$HOME/.gtkrc-2.0>).

=item B<--exec>, B<-e>

Execute the C<Exec=> action from the xsessions file instead of returning
a string indicating the selected xsession.

=back

=head1 ARGUMENTS

B<xde-chooser> take the following arguments:

=over

=item I<SESSION>

The name of the XDG session to execute.  This can be any of the
recognized session names or the special names: C<default> or C<choose>.

=over

=item C<default>

means to execute the default session (typically without
prompting).

=item C<choose>

means to launch a graphical menu so that the use may choose a
session.

=back

When unspecified, the default is C<default>.

A session name is the name of the F<*.desktop> file (without the
F<.desktop> suffix) that exists in a F<@XDG_DATA_DIRS/xsessions/>
directory describing the window manager session.
Some commonly recognized session names are as follows: C<fluxbox>,
C<blackbox>, C<openbox>, C<icewm>, C<pekwm>, C<jwm>, C<metacity>,
C<fvwm>, C<wmaker> and C<afterstep>.

=back

=head1 WINDOW MANAGERS

The I<XDE> suite ships with a number of session files that are contained
in the F</usr/share/xde/xsessions> directory.  Currently these are:
F<AfterStep>, F<blackbox>, F<fluxbox>, F<Fvwm1>, F<fvwm-crystal>,
F<Fvwm>, F<fvwm>, F<gnome>, F<icewm-session>, F<Jwm>, F<LXDE>,
F<openbox>, F<openbox-gnome>, F<openbox-kde>, F<pekwm>, F<ssh>, F<twm>,
F<wmaker>, F<wmii>, F<xfce>.

=head1 FILES

=over

=item F<@XDG_DATA_DIRS/xsessions/*.desktop>

These locations are searched for F<.desktop> files that describe which X
Sessions are to be made available to the user.  Files in this directory
can be desktop files of type I<Application> or I<XSession>.  A I<Window
Manager> section may also describe whether the session needs to be
managed or whether the window manager is capable of managing its own
session.  Desktop entry files in data directories earlier in the search
path override desktop entry files of the same filename later in the
search path.

The I<XDE> suite ships with a number of F<*.desktop> files that are
installed into the F</usr/share/xde/xsessions> directory and are used to
override those for I<gdm> that are normally contained in
F</usr/share/xsessions>.  (To do this, B<xde-chooser> prepends the path
F</usr/share/xde> to the B<XDG_DATA_DIRS> environment variable.)

For a set of these window managers, B<xde-chooser> will execute
L<xde-startup(1)> with the session as an argument.  See
L<xde-startup(1)/WINDOW MANAGERS> for a list of supported window
managers.

=item F<$XDG_CONFIG_HOME/xde/default>

This file contains the default session.  The file consists of a single
line containing the session name.

=item F<$XDG_CONFIG_HOME/xde/current>

This file contains the current session.  The file consists of a single
line containing the session name.

=back

=head1 ENVIRONMENT

=over

=item B<XDG_DATA_HOME>

Specifies the user XDG data directory.  When unspecified, defaults to
F<$HOME/.local/share> in accordance with XDG specifications.
B<xde-chooser> uses this directory to determine the list of default data
directories to search.

=item B<XDG_DATA_DIRS>

Specifies the system XDG data directories.  When unspecified, defaults
to F</usr/local/share:/usr/share> in accordance with XDG specifications.
The directory F</usr/share/xde> will be prefixed to the path unless the
directory is already a component of the path.
B<xde-chooser> uses these directories to determine the list of default
data directories to search.

=item B<XDG_CONFIG_HOME>

Specifies the user XDG configuration directory.  When unspecified,
defaults to F<~/.config> in accordance wtih XDG specifications.
B<xde-chooser> uses this directory to find its configuration files that
are located under F<$XDG_CONFIG_HOME/xde>.

=item B<XDG_CONFIG_DIRS>

Specifies the system XDG configuration directory.  When unspecified,
defaults to F</etc/xdg> in accordance with XDG specifications.
The directory F</etc/xdg/xde> will be prefixed to the path unless the
directory is already a component of the path.
B<xde-chooser> uses these directories to determine the list of default
configuration directories to search.

=back

=head1 USAGE

B<xde-chooser> is meant to be called directly from an F<~/.xinitrc>
file, or from a display manager such as L<slim(1)>.

=head1 BUGS

B<xde-chooser> should really output the path to the F<XSessions> file
instead of the lowercase session name.

=head1 HISTORY

I wrote B<xde-chooser> to provide a mechanism for selecting availabile
window managers in an XDG compliant way for the I<unexicon> desktop.
With L<gdm(1)> going to GTK3, the I<unexicon> desktop uses L<xdm(1)>,
L<slim(1)> and L<xde-chooser(1p)> instead.

=head1 AUTHOR

Brian Bidulock <bidulock@cpan.org>

=head1 SEE ALSO

L<Getopt::Long(3pm)>,
L<xde-logout(1)>,
L<lxsession-logout(1)>,
L<xde-startup(1)>,
L<XDE::Chooser(3pm)>.

=cut
