=pod

=head1 NAME

xde-xlock - screen locker for X Desktop Environment (XDE)

=head1 SYNOPSIS

B<xde-xlock> [I<OPTIONS>]

=head1 DESCRIPTION

B<xde-xlock> is a screen locker replacement that provides tight
integration with the L<systemd(8)> multi-session environment.  It acts as
a screen-saver locker, detects L<logind(8)> C<Lock> signals, and
performs locking on VT switches.

=head1 OPTIONS

No options are necessary.  When launched by L<xdm(1)>, it will provide
the appropriate arguments.  B<xde-xlock> can be launched directly on
the command line of an x-terminal to test its appearance and operation.
In this mode, arguments are still required but no options.  Absence of
the B<-xdmAddress>, B<-clientAddress> and B<-connectionType> options
indicates to B<xde-xlock> that it was not launched by L<xdm(1)> or an
L<xdm(1)> work-alike as a chooser.  See L</USAGE> for more information.

=head2 COMMAND OPTIONS

Command options affect the major operating mode of the program.  Only
one command option may be specified (with the exception that B<--help>
can be specified in conjunction with any other command option).
When no command option is specified, B<--locker> is assumed.
The command options recognized by the program are as follows:

=over 4

=item [B<-L>, B<--locker>]

Run continuously as a screen locker instance.  This process will monitor
for screen locking requests, screen saver activation and virtual
terminal changes and will invoke screen locking as appropriate.

=item B<-r>, B<--replace>

Replace a currently running screen locker instance with the current
process.

=item B<-l>, B<--lock>

Ask a running instance to lock the screen now.

=item B<-q>, B<--quit>

Ask a running instance to exit.

=item B<-H>, B<-help>

Instead of operating normally, the program prints usage information to
standard output and exits.

=item B<-V>, B<--version>

Instead of operating normally, the program prints detailed version
information and exits.

=item B<-C>, B<--copying>

Instead of operating normally, the program prints detailed copying
permissions and exits.

=back

=head2 GENERAL OPTIONS

B<xde-xlock> provides a set of general options that are not supported
by the L<xdm(1)> greeter or chooser.  To supply these options requires
an intermediate script that specifies them and echoes the L<xdm(1)>
chooser options.  So that an intermediate script is not necessary,
L<xdm(1)> provides an F<Xresources> files containing X resources that
are used instead of command line options to tailor the look and feel of
the greeter and chooser.  As a result, the use of the following command
line options are not necessary and are really only used for testing.

The following are the more general options:

=over 4

=item B<-p>, B<--prompt> I<MARKUP>

Specifies the F<pango> markup text that is to be displayed in the title
area of the panel.
When unspecified, the default welcome text is C<Welcome to %s!>, where C<%s>
is the fully qualified domain name of the local host.

=item B<-b>, B<--banner> I<BANNER>

Specifies the banner graphic to display in the left pane of the panel.

The default is obtained by looking for the file
F<${XDG_MENU_PREFIX}banner.{xpm,png,jpg,svg}> in the F<images>
subdirectory of standard XDG data directories, F<$XDG_DATA_DIRS>.  See
L</ENVIRONMENT>.

=item B<-S>, B<--splash> I<SPLASH>

Specifies the background image, I<SPLASH>, to display on the screen.
The default is to use the background image currently installed on the
screen, and if no background image is installed on the screen, to search
for the background image file in the file named
F<${XDG_MENU_PREFIX}splash.{xpm,png,jpg,svg}> in the F<images>
subdirectory of standard XDG data directories, F<$XDG_DATA_DIRS>.  See
L</ENVIRONMENT>.

=item B<-s>, B<--side> {B<left>|B<top>|B<right>|B<bottom>}

Specifies the side on which to display branding (the banner graphic).
Can be one of I<top>, I<left>, I<bottom> or I<right>.  When unspecified,
the default is I<left>.

=item B<--charset> I<CHARSET>

Specifies the character set to use.  When unspecified, the character
set is determined using the current locale: see L<locale(7)>.

=item B<--language> I<LANGUAGE>

Specifies the language to use.  When unspecified, the language is
determined using the current locale: see L<locale(7)>.

=item B<-i>, B<--icons> I<ICON-THEME>

Specifies the GTK+ icon theme to use.  When unspecified, the icon theme
is automatically determined using desktop and toolkit files.

=item B<-T>, B<--theme> I<GTK2-THEME>

Specifies the GTK+ theme name to use.  When unspecified, the GTK2 theme
is automatically determined using desktop and toolkit files.

=item B<-u>, B<--xde-theme>

Specifies that the GTK+ icon theme and theme name to be used are those
of the X Desktop Environment (XDE) rather than the system default theme.
The default is to specify this flag.

=item B<--vendor> I<VENDOR>

Specifies the vendor identifier for branding.  The default, when
unspecified, is to used the value of environment variables
B<XDG_VENDOR_ID> and B<XDG_MENU_PREFIX> to determine the vendor name and
prefix.

=item B<-X>, B<--xsessions>

Specifies that available X sessions (window managers) should be provided
as a menu on the login window.  This allows a user to select an
available session before logging in.

=item B<--default> I<DEFAULT>

Specifies the default X session (window manager) name that should be
used when no X session is selected by the user.  This default is fed as
an argument to F<~/.xinitrc>.

=item B<--username> I<USERNAME>

Specifies the default user name for login.

=item B<--nosetbg>

Specifies that the background image should not be set by the program.
The default behaviour is to set the background in accordance with the
B<-banner> option.

=item B<-transparent>

Specifies that the login panel should be transparent and that the
widgets should be embedded in the background image.  The default is to
paint the login panel.

=item B<-n>, B<--dry-run>

Specifies that the program should not perform any actions but should
simply print intentions to standard output.  This option is for testing.

=item B<-D>, B<--debug> [I<LEVEL>]

Increase, or set to I<LEVEL>, the debugging verbosity.  The default
debugging verbosity level is zero (0), which means to output no
debugging information.  When non-zero, debugging information will be
printed to standard error.

=item B<-v>, B<--verbose> [I<LEVEL>]

Increase, or set to I<LEVEL>, the output verbosity.  The default output
verbosity level is one (1), which means to output normal information to
standard output.  When set to zero (0), no output will be printed to
standard output. 

=back

=head1 USAGE

The B<--locker> command option (the default), or the B<--replace>
option, can be used to run the program as a background screen locker.
In this mode the program installs itself as follows:

=over 4

=item 1.

If possible, takes ownership of the B<_XDE_XLOCK_S>C<%d> manager
selections for each screen on the display.  If one of these manager
selections is already owned, the program exits with a diagnostic unless
B<--replace> was specified as a command option.

=item 2.

Installs itself as a screen saver using the C<MIT-SCREEN-SAVER>
extension on the X server (if present).

=item 3.

Installs itself as a monitoring program on the controlling terminal for
virtual terminal switches (when the X server is running on a local
virtual terminal).

=item 4.

Listens for a C<Lock> signal from the L<systemd(8)> L<logind(8)>
D-BUS service.

=item 5.

Monitors for changes.

=back

When monitoring for changes, the screen locker responds as follows:

=over 4

=item 1.

When it receives a lock request from another instance of the program, it
locks the screen immediately.

=item 2.

When the screen saver is activated, it waits for a number of seconds
after the activation and locks the screen.

=item 3.

When a C<Lock> signal is received from L<logind(8)>, over the D-BUS, it
locks the screen.

When an C<Unlock> signal is received from L<logind(8)>, over the D-BUS,
it unlocks the screen.

=item 4.

When a virtual terminal change is made to the VT on which the X server
is running, it locks the screen before permitting the switch.

=back

The B<--quit> option can be used to ask a running instance of the screen
locker to quit (remove itself and exit).

The B<--lock> option can be used to ask a running instance of the screen
locker to lock the screen.

=head1 X RESOURCES

Most values that affect the look and feel of B<xde-xlock> may also be
specified as X resources in the B<RESOURCE_MANAGER> database associated
with the X server.  All of these resources can have the specific
resource name and class (C<xde-xlock>, B<XDE-XLock>).  When no resource
is found with the specific name and class, L<xdm(1)> resources with name
and class (C<xlogin.login>, C<Xlogin.login>) will also be examined for
specified resources.

Note that L<xdm(1)> usually adds the resources contained in the
F</etc/X11/xdm/Xresources> file that is loaded by L<xdm(1)> on startup
to the resource database on the X server.  Chooser resource defaults
(see also L<xdm(1)> and L<xde-xchooser(1)>) are contained in the
F</usr/share/X11/app-defaults/Chooser> file.  Likewise, B<xde-xlock>
specific resource defaults are contained in the
F</usr/share/X11/app-defaults/XDE-XLock> file, in accordance with the
convention of naming applications default files after their resource
class.  See also L</FILES>.

B<xde-xlock> observes the following X11 Resource Manager resources when
loaded by L<xdm(1)> prior to execution:

=over 4

=item B<xde-xlock>.B<x>: I<DOUBLE>

Specifies the X position on the monitor as a floating point number
between C<0.0> and C<1.0>, where C<0.0> represents the left edge of the
monitor and C<1.0>, the right edge.  The dialog will be positioned on this
point depending on its gravity (currently static or centered).

=item B<xde-xlock>.B<y>: I<DOUBLE>

Specifies the Y position on the monitor as a floating point number
between C<0.0> and C<1.0>, where C<0.0> represents the top edge of the
monitor and C<1.0>, the bottom edge.  The dialog will be positioned on
this point depending on its gravity (currently static or centered).

=item B<xde-xlock>.B<debug>: I<INTEGER>

Provides the debugging level in the same fashion as the B<-debug>
command line option.

=item B<xde-xlock>.B<banner>: I<PATH>

Provides the banner to use for the branding logo in the same fashion as
the B<-banner> command line option.  Specifies the I<PATH> to the banner
graphic to display in the left pane of the host menu.  When unspecified,
the program searches for an image file name
F<${XDG_VENDOR_ID--}banner.{xpm,png,jpg,svg}> in the subdirectory
F<images> in XDG data directories.

=item B<xde-xlock>.B<splash>: I<PATH>

Provides the background to use for the root window in the same fashion
as the B<-splash> command line option.

=item B<xde-xlock>.B<welcome>: I<MARKUP>

Provides the welcome message to use for the root window in the same
fashion as the B<--prompt> command line option.  Specifies the F<pango>
markup text, I<MARKUP>, that is to be display in the title area of the
host menu.

=item B<xde-xlock>.B<charset>: I<CHARSET>

Provides the character set in the same fashion as the B<--charset>
command line option.

=item B<xde-xlock>.B<language>: I<LANG>

Provides the language in the same fashion as the B<--language> command
line option.

=item B<xde-xlock>.B<theme.icon>: I<NAME>

Provides the XDG icon theme name.
Specifies the value of the B<--icons> option.

=item B<xde-xlock>.B<theme.name>: I<NAME>

Provides the XDG theme name (for GTK+).
Specifies the value of the B<--theme> option.

=item B<xde-xlock>.B<theme.cursor>: I<NAME>

Provides the XDG cursor theme name.

=item B<xde-xlock>.B<theme.xde>: {B<true>|B<false>}

When I<true>, specifies that the system XDE desktop theme should be used
instead of the system GTK+ theme.
Specifies the value of the B<--xde-theme> option.

=item B<xde-xlock>.B<side>: {B<left>|B<right>|B<top>|B<bottom>}

Specifies the side on which the logo (banner) should appear.  Currently
only I<left> is supported.
Specifies the value of the B<-side> option.

=item B<xde-xlock>.B<user.default>: I<USERNAME>

Specifies a default use name to use for the login (when a login is
provided).  Note that a default user name will not be presented when it
can be detected that the display is remote from the current host.
Specifies the value of the B<--username> option.

=item B<xde-xlock>.B<autologin>: {B<true>|B<false>}

When I<true>, specifies that the user defined in
B<xde-xlock>.B<user.default> should be automatically logged into a
session without requiring a password.  It may be necessary for such a
user to be a member of the C<autologin> group.  Auto login will be
suppressed when it can be detected that the display is remote from the
current host.

=item B<xde-xlock>.B<vendor>: I<VENDOR-ID>

Provides a vendor identifier for use in lookup up banners and
backgrounds automatically, as with the B<--vendor> command line option.

=item B<xde-xlock>.B<prefix>: I<MENU-PREFIX>

Provides a vendor identifier as a menu prefix (C<XDG_MENU_PREFIX>)
instead of as a plain identifier.  The prefix normally has a dash (C<->)
appended.

=item B<xde-xlock>.B<login>.B<permit>: {B<true>|B<false>}

The XDMCP Chooser has control of an X Display in the same manner as the
XDMCP Greeter program and may provide an immediate login option in
addition to a list of XDMCP hosts.  When I<true>, this option specifies
that this login is to be presented as an option to users of the XDMCP
Chooser.

=item B<xde-xlock>.B<login>.B<remote>: {B<true>|B<false>}

The XDMCP Chooser may provide a direct login option to the user of the
chooser.  When I<true>, this option specifies that remote displays will
be given the same opportunity to log in directly.  When I<false>,
displays that are detected as remote from the host will no be offered a
direct login.

=item B<xde-xlock>.B<xsession.chooser>: {B<true>|B<false>}

Specifies the value of the B<--xsessions> option.

=item B<xde-xlock>.B<xsession.execute>: {B<true>|B<false>}

=item B<xde-xlock>.B<xsession.default>: I<APPID>

Specifies the value of the B<--default> option.

=item B<xde-xlock>.B<setbg>: {B<true>|B<false>}

Specifies the value of the B<--nosetbg> option.

=item B<xde-xlock>.B<transparent>: {B<true>|B<false>}

Specifies the value of the B<-transparent> option.

=item B<xde-xlock>.B<face>: I<XFTFONT>

The typeface used to display the input typed by the user.
The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.face>
resource is used instead.

=item B<xde-xlock>.B<greetFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.greetFace>
resource is used instead.

=item B<xde-xlock>.B<greetColor>

The default is C<grey20>.
If this resource is not specified, the
B<xlogin>.B<Login.greetColor>
resource is used instead.

=item B<xde-xlock>.B<promptFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.promptFace>
resource is used instead.

=item B<xde-xlock>.B<promptColor>

The default is C<grey20>.
If this resource is not specified, the
B<xlogin>.B<Login.promptColor>
resource is used instead.

=item B<xde-xlock>.B<inputFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.inputFace>
resource is used instead.

=item B<xde-xlock>.B<inputColor>

The default is C<grey20>.
If this resource is not specified, the
B<xlogin>.B<Login.inputColor>
resource is used instead.

=item B<xde-xlock>.B<failFace>

The default is C<Sans:size=12:bold>.
If this resource is not specified, the
B<xlogin>.B<Login.failFace>
resource is used instead.

=item B<xde-xlock>.B<failColor>

The default is C<red>.
If this resource is not specified, the
B<xlogin>.B<Login.failColor>
resource is used instead.

=back

When specific B<xde-xlock> resources are not specified,
B<xde-xlock> falls back the using the resources specified for its
default greeter by L<xdm(1)>, as follows:

=over 4

=item B<xlogin>.B<Login.width>: I<INTEGER>

Specifies the width of the login widget, either in pixels, or when
suffixed with a C<%>, as a decimal percentage of the display width.
The default is dynamic width, depending on the contents of widgets.

=item B<xlogin>.B<Login.height>: I<INTEGER>

Specifies the height of the login widget, either in pixels, or when
suffixed with a C<%>, as a decimal percentage of the display height.
The default is dynamic height, depending on the contents of widgets.

=item B<xlogin>.B<Login.x>: I<INTEGER>

Specifies the x-axis position of the login widget.
The default is centred on the screen.

=item B<xlogin>.B<Login.y>: I<INTEGER>

Specifies the y-axis position of the login widget.
The default is centred on the screen.

=item B<xlogin>.B<Login.foreground>: I<XCOLOR>

The foreground colour used to display the input typed by the user.
The default is C<grey20>.

=item B<xlogin>.B<Login.background>: I<XCOLOR>

The background colour used to display the input typed by the user.
The default is C<LightSteelBlue3>.

=item B<xlogin>.B<Login.face>: I<XFTFONT>

The typeface used to display the input typed by the user when built with
Xft support.
The default is C<Sans:size=12:bold>.

=item B<xlogin>.B<Login.font>: I<XFONT>

The font used to display the input typed by the user when not built with
Xft support.
This resource not used by B<xde-xlock>.

=item B<xlogin>.B<Login.greeting>: I<STRING>

A string that identifies this window.  The L<xdm(1)> default is C<X
Window System>.
The default is the value specified by command line option B<--prompt>,
or C<Welcome to CLIENTHOST>.

=item B<xlogin>.B<Login.unsecureGreeting>: I<STRING>

When X authorization is requested in the configuration file for this
display and none is in use, this greeting replaces the standard
greeting.
The default is C<This is an unsecure session>.

=item B<xlogin>.B<Login.greetFace>: I<XFTFONT>

The face used to display the greeting when built with Xft support.  The
L<xdm(1)> default is C<Serif-24:italic>.
The default is C<Sans:size=12:bold>.

=item B<xlogin>.B<Login.greetFont>: I<XFONT>

The font used to display the greeting when not built with Xft support.
This resource not used by B<xde-xlock>.

=item B<xlogin>.B<Login.greetColor>: I<XCOLOR>

The color used to display the greeting.
The default is C<grey20>.

=item B<xlogin>.B<Login.namePrompt>: I<STRING>

The string display to prompt for a user name.  L<xrdb(1)> strips
trailing white space from resource values, so to add spaces at the end
of the prompt (usually a nice thing), add spaces escaped with
backslashes.  The L<xdm(1)> default is C<Login:  >.
The default is C<Username:  >.

=item B<xlogin>.B<Login.passwdPrompt>: I<STRING>

The string displayed to prompt for a password, when not using an
authentication system such as PAM that provides its own prompts.  The
L<xdm(1)> default is C<Password:  >.
The default is C<Password:  >.

=item B<xlogin>.B<Login.promptFace>: I<XFTFONT>

The face used to display prompts when build with Xft support.  The
L<xdm(1)> default is C<Serif-18:bold>.
The default is C<Sans:size=12:bold>.

=item B<xlogin>.B<Login.promptFont>: I<XFONT>

The font used to display prompts when not built with Xft support.
This resource not used by B<xde-xlock>.

=item B<xlogin>.B<Login.promptColor>: I<XCOLOR>

The color used to display prompts.
The default is C<grey20>.

=item B<xlogin>.B<Login.inputFace>: I<XFTFONT>

The face used to display user input when built with Xft support.
The default is C<Sans:size=12:bold>.

=item B<xlogin>.B<Login.inputFont>: I<XFONT>

The font used to display user input when not built with Xft support.
This resource not used by B<xde-xlock>.

=item B<xlogin>.B<Login.inputColor>: I<XCOLOR>

The color used to display user input.
The default is C<grey20>.

=item B<xlogin>.B<Login.changePasswdMessage>: I<STRING>

A message that is displayed when the user's password has expired.  The
L<xdm(1)> default is C<Password Change Required>.
The default is supplied by the PAM subsystem.

=item B<xlogin>.B<Login.fail>: I<STRING>

A message that is displayed when the authentication fails, when not
using an authentication system such as PAM that provides its own
prompts.  The L<xdm(1)> default is C<Login incorrect>.
The default is supplied by the PAM subsystem.

=item B<xlogin>.B<Login.failFace>: I<XFTFONT>

The face used to display the failure message when built with Xft
support.  The L<xdm(1)> default is C<Serif-18:bold>.
The default is C<Sans:size=12:bold>.

=item B<xlogin>.B<Login.failFont>: I<XFONT>

The font used to display the failure message when not built with Xft
support.
This resource not used by B<xde-xlock>.

=item B<xlogin>.B<Login.failColor>: I<XCOLOR>

The default color used to display the failure message.
The default is C<red>.

=item B<xlogin>.B<Login.failTimeout>: I<INTEGER>

The number of seconds that the failure message is displayed, before
another login attempt is permitted.
The L<xdm(1)> default is C<10>.
The PAM subsystem provides this delay.

=item B<xlogin>.B<Login.logoFileName>: I<PATH>

Name of an XPM format pixmap to display in the greeter window, if built
with XPM support.  The L<xdm(1)> default is no pixmap.
The default is F</etc/X11/xdm/xde/banner.png>.

=item B<xlogin>.B<Login.logoPadding>: I<INTEGER>

The number of pixels of space between the logo pixmap and other elements
of the greeter window, if the pixmap is displayed.  The L<xdm(1)>
default is C<5>.
The default is C<8>.

=item B<xlogin>.B<Login.useShape>: {B<true>|B<false>}

If set to C<true>, when built with XPM support, attempt to use the X
Non-Rectangular window Shape Extension to set the window shape.  The
L<xdm(1)> default is C<true>.
The default is C<true>.

=item B<xlogin>.B<Login.hiColor>: I<XCOLOR>

Raised appearance bezels may be drawn around the greeter frame and text
input boxes by setting this resource.
B<hiColor> is the highlight color, used on the top and left sides of the
frame, and the bottom and right sides of the text input areas.
The L<xdm(1)> default is the foreground color, providing a flat
appearance.
The default is C<grey80>.
This GTK+ version defaults to the active GTK theme.

=item B<xlogin>.B<Login.shdColor>: I<XCOLOR>

Raised appearance bezels may be drawn around the greeter frame and text
input boxes by setting this resource.
B<shdColor> is the shadow color, used on the bottom and right sides of
the frame, and the top and left sides of the text input areas.
The L<xdm(1)> default is the foreground color, providing a flat
appearance.
The default is C<grey20>.
This GTK+ version defaults to the active GTK theme.

=item B<xlogin>.B<Login.frameWidth>: I<INTEGER>

The width in pixels of the area around the greeter frame drawn in
B<hiColor> and B<shdColor>.
For GTK, when set to C<0>, the frame will be drawn flat; otherwise, it
will be drawn raised.
The default is C<2>.

=item B<xlogin>.B<Login.innerFrameWidth>: I<INTEGER>

The width in pixels of the area around text input areas drawn in
B<hiColor> and B<shdColor>.
The default is C<2>.
For GTK, when set to C<0>, the text areas will be drawn flat; otherwise,
they will be drawn sunken.

=item B<xlogin>.B<Login.sepWidth>: I<INTEGER>

The width in pixels of the bezel line between the greeting and input
areas drawn in B<hiColor> and B<shdColor>.
For GTK, when set to C<0>, the line will be drawn flat; otherwise it
will be drawn etched.
The default is C<2>.

=item B<xlogin>.B<Login.allowRootLogin>: {B<true>|B<false>}

When set to C<false>, do not allow root (and any other user with uid of
zero) to log in directly.
This setting is only checked by some authentication back-ends at this
time.
The default is C<true>.
This option is better set using the C<xdm-login> PAM service settings.

=item B<xlogin>.B<Login.allowNullPasswd>: {B<true>|B<false>}

If set to C<true>, allow an otherwise failing password match to succeed
if the account does not require a password at all.  The default is
C<false>, so only users that have passwords assigned can log in.
This option is better set using the C<xdm-login> PAM service settings.

=item B<xlogin>.B<Login.echoPasswd>: {B<true>|B<false>}

When set C<true>, a placeholder character (B<echoPasswdChar>) will be
shown for fields normally set to not echo, such as password input.  The
L<xdm(1)> default is C<false>.
The default is C<true>.

=item B<xlogin>.B<Login.echoPasswdChar>: I<STRING>

Character to display if B<echoPasswd> is C<true>.  The default is C<*>.
When set to an empty value, the cursor will advance for each character
input, but no text will be drawn.

=item B<xlogin>.B<Login.borderWidth>: I<INTEGER>

The width in pixels between the edge of the greeter frame and its
content.
The default is C<3>.

=item B<xlogin>.B<Login.translations>: I<STRING>

This resource not used by B<xde-xlock>.

=back

=head1 CONFIGURATION

L<xdm(1)> specifies which chooser and greeter to execute in its
configuration file F</usr/lib/X11/xdm/xdm-config>:

=over 4

=item B<DisplayManager>.I<DISPLAY>.B<chooser>

This option, described in L<xdm(1)>, is used to tell L<xdm(1)> which
program to run as a chooser.  This should be set to
F</usr/bin/xde-xlock>.  See L<xdm(1)/CHOOSER>.

=item B<DisplayManager>.I<DISPLAY>.B<greeter>

This option, described in L<xdm(1)>, is used to tell L<xdm(1)> which
program to run as a greeter.  This should be set to
F</usr/bin/xde-xlock>.  See L<xdm(1)/AUTHENTICATION WIDGET>.

=back

=head1 FILES

The following files are used by the program:

=over 4

=item F</usr/bin/xde-xlock>

The default location of the B<xde-xlock> executable.
As this is useful for normal users, it resides in the
F</usr/bin> directory.

=item F<$XDG_DATA_DIRS/images/${XDG_MENU_PREFIX}banner.png>

The default location of the banner graphic.

=item F<$XDG_DATA_DIRS/images/${XDG_MENU_PREFIX}splash.png>

The default location of the background splash to display on the lock
screen when no other background is available.

=item F</etc/X11/xdm/Xresources>

The normal location of the X resources file for L<xdm(1)>.  Normally,
L<xdm(1)> will merge the resources found in this file into the X display
B<RESOURCE_MANAGER> property on the root window before launching the
greeter or chooser programs.

=item F</etc/X11/xdm/xde/Xresources>

Because the greeter and chooser is associated with XDE, a complete set of
L<xdm(1)> configuration files, including the X resources file containing
B<XDE-XLock> resources are contained in the F</etc/X11/xdm/xde>
subdirectory.  Application defaults are not loaded from anywhere else
for security.

=item F</usr/share/X11/app-defaults/XDE-XLock>

X resource defaults for B<xde-xlock>.
The program will load the default resources from this file and then
merge the resources specified in the B<RESOURCE_MANAGER> property on the
X display.  L<xdm(1)> will normally use L<xrdb(1)> to merge the
resources from the F</etc/X11/xdm/Xresources> into the
B<RESOURCE_MANAGER> property on the X display before launching the login
or greeter program.

=back

=head1 ENVIRONMENT

The following environment variables are considered by the program:

=over 4

=item B<XDG_VENDOR_ID>

When specified in the environment, the program will use the value of
this environment variable to form the default names of the B<--banner>
and B<--splash> files by prefixing it and a dash (C<->) to the default
banner or splash name.  This environment variable will be used in
preference to B<XDG_MENU_PREFIX> but can be overridden with the
B<--vendor> option.

=item B<XDG_MENU_PREFIX>

When specified in the environment, and neither the B<XDG_VENDOR_ID>
environment variable nor the B<--vendor> option are specified, the
program will use the value of this environment variable to form the
default names of the B<--banner> and B<--splash> files by prefixing it
to the default banner or splash name.  This environment variable will be
overridden by either of the B<XDG_VENDOR_ID> environment variable or
B<--vendor> option.

=item B<XDG_DATA_DIRS>

When specified, specifies the path of XDG data directories that will be
searched for banner or splash files.  When unspecified, defaults to
F</usr/local/share:/usr/share> in accordance with XDG specifications.

=back

=head1 BUGS

B<xde-xlock> had no known bugs at the time of release.  Please report
bugs for current versions to the source code repository at
L<https://github.com/bbidulock/xde-session/issues>.

=head1 HISTORY

I wrote B<xde-xlock> because there were no stand-alone screen lockers
that worked well with the L<systemd(8)> multi-session environment.

=head1 SEE ALSO

L<xdm(1)>,
L<xqproxy(1)>,
L<xde-xlogin(1)>,
L<xde-xchooser(1)>,
L<slim(1)>,
L<xde-xlock(1)>,
L<Xnest(1)>,
L<Xephyr(1)>,
L<X Display Manager Control Protocol>.

=head1 AUTHOR

Brian Bidulock L<mailto:bidulock@openss7.org>.

See B<--copying> for full copyright notice and copying permissions.

=head1 LICENSE

See the F<COPYING> file in the distribution or use the B<--copying> flag
to display copying permissions.

=cut

# vim: set sw=4 tw=72 nocin spell spelllang=en_ca:
