#!/bin/bash

here="$(dirname $0)"
case "$here" in /*) ;; *) here=`(cd "$here"; pwd)` ;; esac

name=ctwm
files="apps buttons defaults keys menu stylemenu version winmenu"
progs="config getstyles setstyle start"
udirs="pixmaps styles"

[ -n "$XDG_CONFIG_HOME" ] || XDG_CONFIG_HOME="$HOME/.config"
[ -n "$XDG_DATA_HOME"   ] || XDG_DATA_HOME="$HOME/.local/share"
[ -n "$XDG_CONFIG_DIRS" ] || XDG_CONFIG_DIRS="/etc/xdg"
[ -n "$XDG_DATA_DIRS"   ] || XDG_DATA_DIRS="/usr/local/share:/usr/share"

prog=${1:-${TWM_TYPE:-$name}}
if [ ! -x "`which $prog 2>/dev/null`" ]; then
    echo "ERROR: cannot find usable $prog program" >&2
    exit 1
fi
vers=${2:-${TWM_VERSION}}
if [ -z "$vers" ]; then
    if $prog -version >/dev/null 2>&1; then
	vers=$(LANG= $prog -version 2>/dev/null)
    else
	vers='3.8.1'
    fi
fi
sdir="${TWM_CONFIG_SDIR:-/usr/share/$prog}"
if [ -z "$XDG_USE_XDG_HOME" ]; then
    path="${TWM_CONFIG_HOME:-${HOME:-~}/.$prog}"
else
    path="${TWM_CONFIG_HOME:-${XDG_CONFIG_HOME:-${HOME:-~}/.config}/$prog}"
fi
export TWM_TYPE="$prog"
export TWM_VERSION="$vers"
export TWM_CONFIG_HOME="$path"
export TWM_CONFIG_SDIR="$sdir"
export TWM_CONFIG_EDIR="$here"

[ -d "$path" ] || mkdir -p "$path"
if [ -s "$here/version" ]; then
    if [ ! -s "$path/version" -o ! diff "$here/version" "$path/version" ]; then
	for f in $files; do
	    if [ ! -f "$here/$f" -o ! diff "$here/$f" "$path/$f" ]; then
		[ ! -f "$path/$f" ] || /bin/mv -f "$path/$f" "$path/$f.bak"
		case " $progs " in
		*" $f "*) ;;
		*) sed -e "s,\~/\.$name,$path,;s,\$HOME/\.$name,$path,;s,~/,$HOME/," "$path/$f" "$here/$f" >"$path/$f" ;;
		esac
	    fi
	done
	for u in $udirs; do
	    [ -d "$u" ] || mkdir -p "$u"
	done
	(cd "$path"; md5sum $files >.versions)
    fi
fi

desktop=$(echo "$prog"|sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/')

if [ -x "`which xdg-menugen 2>/dev/null`" ]; then
    xdg-menugen --format "$prog" --desktop "$desktop" -o "$path/menu" &
elif [ -x "`which xde-menugen 2>/dev/null`" ]; then
    xde-menugen --format "$prog" --desktop "$desktop" >"$path/menu" &
fi

config="$here/config"
[ -x "$config" ] || config="$path/config"
[ -x "$config" ] || config="$sdir/config"
[ -x "$config" ] || config="$here/config"
[ -x "$config" ] && $config

getstyles="$here/getstyles"
[ -x "$getstyles" ] || getstyles="$path/getstyles"
[ -x "$getstyles" ] || getstyles="$sdir/getstyles"
[ -x "$getstyles" ] || getstyles="$here/getstyles"
[ -x "$getstyles" ] && $getstyles

export TWM_RCFILE="${HOME:-~}/.${prog}rc"

if [ -L "$TWM_RCFILE" ]; then
    /bin/rm -f "$TWM_RCFILE"
elif [ -s  "$TWM_RCFILE" ]; then
    /bin/mv -f "${TWM_RCFILE}" "${TWM_RCFILE}.bak"
fi
/bin/ln -sf "$path/rc.m4" "$TWM_RCFILE"

exit 0

# vim: set ft=sh sw=4:
