#!/bin/bash

here="$(dirname $0)"
case "$here" in /*) ;; *) here=`(cd "$here"; pwd)` ;; esac

name=waimea
files="version actionrc config menu winmenu"
progs="start"
udirs="styles"

[ -n "$XDG_CONFIG_HOME" ] || XDG_CONFIG_HOME="$HOME/.config"
[ -n "$XDG_DATA_HOME"   ] || XDG_DATA_HOME="$HOME/.local/share"
[ -n "$XDG_CONFIG_DIRS" ] || XDG_CONFIG_DIRS="/etc/xdg"
[ -n "$XDG_DATA_DIRS"   ] || XDG_DATA_DIRS="/usr/local/share:/usr/share"

prog=${1:-${XDE_WM_TYPE:-$name}}
if [ ! -x "`which $prog 2>/dev/null`" ]; then
    echo "ERROR: cannot find usable $prog program" >&2
    exit 1
fi
vers=${2:-${XDE_WM_VERSION}}
if [ -z "$vers" ]; then
    if $prog --version >/dev/null 2>&1; then
	vers=$(LANG= $prog --version 2>/dev/null|awk '/waimea/{print$2;exit}')
    else
	vers="0.5.0"
    fi
fi
sdir="${XDE_WM_CONFIG_SDIR:-/usr/share/$prog}"
if [ -z "$XDG_USE_XDG_HOME" ]; then
    path="${XDE_WM_CONFIG_HOME:-${HOME:-~}/.$prog}"
else
    path="${XDE_WM_CONFIG_HOME:-${XDG_CONFIG_HOME:-${HOME:-~}/.config}/$prog}"
fi
export XDE_WM_TYPE="$prog"
export XDE_WM_VERSION="$vers"
export XDE_WM_CONFIG_HOME="$path"
export XDE_WM_CONFIG_SDIR="$sdir"
export XDE_WM_CONFIG_EDIR="$here"

[ -d "$path" ] || mkdir -p "$path"
if [ -s "$here/version" ]; then
    if [ ! -s "$path/version" -o ! diff "$here/version" "$path/version" ]; then
	for f in $files; do
	    if [ ! -f "$here/$f" -o ! diff "$here/$f" "$path/$f" ]; then
		[ ! -f "$path/$f" ] || /bin/mv -f "$path/$f" "$path/$f.bak"
		case " $progs " in
		*" $f "*) ;;
		*) sed -e "s,\~/\.$name,$path,;s,\$HOME/\.$name,$path,;s,~/,$HOME/," "$path/$f" "$here/$f" >"$path/$f" ;;
		esac
	    fi
	done
	for u in $udirs; do
	    [ -d "$u" ] || mkdir -p "$u"
	done
	(cd "$path"; md5sum $files >.versions)
    fi
fi

desktop=$(echo "$prog"|sed 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/')

if [ -x "`which xde-menugen 2>/dev/null`" ]; then
    xde-menugen --format="$prog" --desktop="$desktop" --output="$path/menu" &
elif [ -x "`which xdg-menugen 2>/dev/null`" ]; then
    xdg-menugen --format="$prog" --desktop="$desktop" --output="$path/menu" &
fi

config="$here/config"
[ -x "$config" ] || config="$path/config"
[ -x "$config" ] || config="$sdir/config"
[ -x "$config" ] || config="$here/config"
[ -x "$config" ] && $config

getstyles="$here/getstyles"
[ -x "$getstyles" ] || getstyles="$path/getstyles"
[ -x "$getstyles" ] || getstyles="$sdir/getstyles"
[ -x "$getstyles" ] || getstyles="$here/getstyles"
[ -x "$getstyles" ] && $getstyles

export XDE_WM_RCFILE="${HOME:-~}/.${prog}rc"

if [ -L "$XDE_WM_RCFILE" ]; then
    /bin/rm -f "$XDE_WM_RCFILE"
elif [ -s "$XDE_WM_RCFILE" ]; then
    /bin/mv -f "${XDE_WM_RCFILE}" "${XDE_WM_RCFILE}.bak"
fi
/bin/ln -sf "$path/config" "$XDE_WM_RCFILE"

exit 0

# vim: set ft=sh sw=4:
