#!/bin/bash

prog=$0
here=$(echo $prog|sed 's,/[^/]*$,,')
here=`(cd "$here"; pwd)`
prog=$(echo "$prog"|sed 's,^.*/,,')

export CTWM_TYPE=${1:-${CTWM_TYPE:-ctwm}}
if [ ! -x "`which $CTWM_TYPE 2>/dev/null`" ]; then
    echo "ERROR: cannot find usable ctwm program" >&2
    exit 1;
fi
if [ -z "$CTWM_VERSION" ]; then
    if $CTWM_TYPE -version >/dev/null 2>&1; then
	CTWM_VERSION=$($CTWM_TYPE -version 2>/dev/null)
    else
	CTWM_VERSION='3.8.1'
    fi
fi
export CTWM_VERSION=${2:-$CTWM_VERSION}
export CTWM_CONFIG_HOME=${CTWM_CONFIG_HOME:-${HOME:-~}/.$CTWM_TYPE}
export CTWM_CONFIG_SDIR=${CTWM_CONFIG_SDIR:-/usr/share/$CTWM_TYPE}

[ -d "$CTWM_CONFIG_HOME" ] || mkdir -p "$CTWM_CONFIG_HOME"
if [ -s "$CTWM_CONFIG_SDIR/version" ]; then
    if [ ! -s "$CTWM_CONFIG_HOME/version" -o ! diff "$CTWM_CONFIG_SDIR/version" "$CTWM_CONFIG_HOME/version" ] ; then
	for file in apps defaults keys menu stylemenu version winmenu; do
	    if [ ! -f "$CTWM_CONFIG_SDIR/$file" -o ! diff "$CTWM_CONFIG_SDIR/$file" "$CTWM_CONFIG_HOME/$file" ] ; then
		[ ! -f "$CTWM_CONFIG_HOME/$file" ] || /bin/mv -f "$CTWM_CONFIG_HOME/$file" "$CTWM_CONFIG_HOME/$file.bak"
		cat "$CTWM_CONFIG_SDIR/$file" \
		    | sed -r 's,\$HOME\>,'"${HOME:-~}"',g' \
		    >"$CTWM_CONFIG_HOME/$file"
	    fi
	done
    fi
fi

if [ -x "`which xde-menugen 2>/dev/null`" ]; then
    xde-menugen --format $CTWM_TYPE >"$CTWM_CONFIG_HOME/menu"
fi

config="$here/config"
[ -x "$config" ] || config="$CTWM_CONFIG_HOME/config"
[ -x "$config" ] || config="$CTWM_CONFIG_SDIR/config"
[ -x "$config" ] && $config

getstyles="$here/getstyles"
[ -x "$getstyles" ] || getstyles="$CTWM_CONFIG_HOME/getstyles"
[ -x "$getstyles" ] || getstyles="$CTWM_CONFIG_SDIR/getstyles"
[ -x "$getstyles" ] && $getstyles

export CTWM_RCFILE="${HOME:-~}/.${CTWM_TYPE}rc"

if [ -L "$CTWM_RCFILE" ]; then
    /bin/rm -f "$CTWM_RCFILE"
elif [ -s  "$CTWM_RCFILE" ]; then
    /bin/mv -f "${CTWM_RCFILE}" "${CTWM_RCFILE}.bak"
fi
/bin/ln -sf "$CTWM_CONFIG_HOME/rc.m4" "$CTWM_RCFILE"

exec $CTWM_TYPE

# vim: sw=4
